### ISSUE TITLE
Support for more ZCL clusters (TZ-91)

### ISSUE THREAD

**Issue by JanUmbach** [espressif/esp-zigbee-sdk#10]
I am interested to a Multistate Input, an Analog Input and a Power Configuration cluster, but these aren't supported yet.

Would be really cool if you could also implement this. (It is related to #6 but I don't know if I should reopen this issue or create a new one for a “cluster request”)

**Comment by likunqiao097304** [comment]
@JanUmbach It is better to create a new one issue for your new ZCL clusters support. We will consider to add those clusters in the next round release

**Comment by likunqiao097304** [comment]
@JanUmbach Just for curiosity, do you have any specific Zigbee devices that you need to those three clusters

**Comment by likunqiao097304** [comment]
@JanUmbach We will support power configure cluster and release this week. But for the rest of two are not mandatory for the base device, so we will put into the future plan but not this time. For details, you can refer to CSA document to check this list : 16-02867-021-PRO_BDB-ZigBee-3.0-Cluster-List.xlsx.
