### ISSUE TITLE
[Feature request] Add write, read command request functions with multiple attributes (TZ-304)

### ISSUE THREAD

**Issue by diazmanuel** [espressif/esp-zigbee-sdk#106]
Hello, 
I was reading the zigbee documentation and it is assumed that it is possible to perform a read or write query for multiple attributes in the same message (this is especially beneficial in cases of low-power applications and optimizations) I leave you the images of the documentation

![MicrosoftTeams-image (4)](https://github.com/espressif/esp-zigbee-sdk/assets/39015966/018ed970-d0fc-4adf-b384-5f2dc1e4357e)

![MicrosoftTeams-image (5)](https://github.com/espressif/esp-zigbee-sdk/assets/39015966/a6539cec-2e50-490a-ac1f-1eb205f09d9c)

thanks

**Comment by xieqinan** [comment]
Hello @diazmanuel,

The feature has been supported in esp-zigbee-lib v1.0.0 [ZCL general command](https://github.com/espressif/esp-zigbee-sdk/blob/main/components/esp-zigbee-lib/include/zcl/esp_zigbee_zcl_command.h#L86)，Could you please try using and testing it?

**Comment by xieqinan** [comment]
Hello @diazmanuel ,

Your suggestion is practical. We plan to fix this issue by ensuring that the `esp_zb_zcl_cmd_read_attr_resp_message_t` will carry the attribute list to the application layer in the upcoming version.

**Comment by diazmanuel** [comment]
hello @xieqinan,
Thanks for taking this into account, it is also necessary to see the case of writing that generates an individual callback just like reading

**Comment by xieqinan** [comment]
@diazmanuel ，

The issue has been fixed in esp-zigbee-sdk [v1.0.2](https://github.com/espressif/esp-zigbee-sdk), please refer to [read attribute message](https://github.com/espressif/esp-zigbee-sdk/blob/main/components/esp-zigbee-lib/include/zcl/esp_zigbee_zcl_command.h#L1256).
