### ISSUE TITLE
ESP32-H2 reading or writing consumption is too high (TZ-306)

### ISSUE THREAD

**Issue by diazmanuel** [espressif/esp-zigbee-sdk#108]
Hello,

I am analyzing the consumption of the ESP32H2 when reading from an external device and I encounter the following consumption problem as seen in the image

![MicrosoftTeams-image (7)](https://github.com/espressif/esp-zigbee-sdk/assets/39015966/e1b0fd1a-dd44-41c4-acc2-a5464860aa02)

So in this image you can see two problems: on the one hand, the type of replica that is observed and on the other hand, the excessive consumption that is maintained for a long time in 20ma. If we zoom in we see the following

![MicrosoftTeams-image (8)](https://github.com/espressif/esp-zigbee-sdk/assets/39015966/6de32c87-cafc-41e1-94ec-56b490cce2e1)

In the zoom, 3 peaks are observed and then an almost constant consumption of approximately 20ma, but the response to the reading ends with those first 3 peaks. That is to say, the response to the data query is carried out with those 3 peaks and for some reason after that it remains at that high consumption for a long time.

Also perform a reading of several attributes with the same command, resulting in the following image.

![MicrosoftTeams-image (9)](https://github.com/espressif/esp-zigbee-sdk/assets/39015966/769a436e-c2e3-4892-906b-081dd206744c)

In this image you can clearly see the 2 queries and you can also see the replica, but this replica is not a replica as was believed, because in this supposed replica you do not see the 2 data consumptions as in the other case.

Also here there is another case in which the chip generates 7 reports and after a moment this 20ma step signal appears as in the rest of the cases

![MicrosoftTeams-image (10)](https://github.com/espressif/esp-zigbee-sdk/assets/39015966/0831cab0-3c44-42d5-9a09-4d24f9bd2969)

The biggest drawback is not the replicas but the high consumption in each interaction with the zigbee layer, whether reading or writing (the operation of the reports with the low consumption methodology still needs to be verified), in addition, as I mentioned before, the response is received with the initial peaks that are seen in the image, and then it remains stuck at 20ma for some other reason, this for low consumption applications represents a serious problem, I would like to know how to solve it, or if they were able to replicate this problem in their tests

thanks

**Comment by kelin6** [comment]
@diazmanuel  May I inquire about the environment in which you are running the Zigbee sleep example, such as the ESP-IDF commit and ESP-Zigbee-SDK version?

We are currently making modifications to the light sleep code internally, based on our latest internal code, our test results are as follows:
![zigbee_sleep](https://github.com/espressif/esp-zigbee-sdk/assets/39639038/5c82b85a-99b2-4fbb-83ac-6803fcee5d76)
![read_attribute](https://github.com/espressif/esp-zigbee-sdk/assets/39639038/ad0e408d-3cd4-4a6d-b72b-e8dd10895900)

- Regarding what you mentioned about the type of replica, it pertains to sending a read attribute command, receiving a response, and sending APS ack/ack packets, which align with a transmit current of 110mA. 

- The excessive power consumption issue within 20mA for long-term maintenance has now been resolved. Next, we will update ESP-IDF and ESP-Zigbee-SDK.

**Comment by diazmanuel** [comment]
Hello!
Thanks for the response, I'm glad to know the problem was found.

I leave you the data of the environment
ESP-IDF: release v5.1
ESP-ZIGBEE-SDK: 0.9.5

May I know when they estimate that these updates will be uploaded to solve the problem and be able to continue testing?

**Comment by kelin6** [comment]
@diazmanuel  The fixed code has already been internally reviewed and merged. It should be visible on GitHub in about 1 to 2 weeks.

**Comment by kelin6** [comment]
@diazmanuel  
Please update the ESP-IDF and ESP-Zigbee-SDK using the following environment:

- ESP-IDF branch: release/v5.1 (commit:  [6b1f40b](https://github.com/espressif/esp-idf/commits/release/v5.1))
- ESP-Zigbee-SDK branch: main(commit: 41c7f14488d7d00cd975b6c2a74128d0840a0193)


Hope this helps you.

**Comment by chshu** [comment]
@diazmanuel Please reopen if any follow up questions.
