### ISSUE TITLE
Setting custom PAN id (TZ-92)

### ISSUE THREAD

**Issue by renzenicolai** [espressif/esp-zigbee-sdk#11]
I'd like to be able to use the ESP32-C6 as a coordinator for an already existing Zigbee device which implements only the bare minimum of the Zigbee protocol.

These devices use a specific PAN id, the ESP32-C6 automatically generates a PAN id during network formation, how can I set the PAN id manually?

Can you add an API interface for setting the PAN id?

**Comment by likunqiao097304** [comment]
@renzenicolai we will add set PAN id api in the next release round.

**Comment by renzenicolai** [comment]
Thank you!
