### ISSUE TITLE
Documentation and Examples on detailed debugging (TZ-325)

### ISSUE THREAD

**Issue by baylf2000** [espressif/esp-zigbee-sdk#113]
Please add some detailed documentation and examples on how to debug the Zigbee software. 

There is the "Zigbee Trace Enable" option in the configs, however the current documentation does not explain what any of those trace messages mean, and many are difficult or impossible to guess.

There should be a simple method to dump all incoming zigbee packets to a debug log *before* they are processed in any way. I have yet to find anything that works. There is `esp_zb_raw_command_handler_register`, but this is not documented, and the examples I have found in these github issues seem to only ever return zero results.

There is a lot that goes on "behind the scenes" with this Zigbee implementation, and it's invisible to the end user because it's a binary implementation. This makes it especially important to make detailed debugging features available and documented.

**Comment by kelin6** [comment]
@baylf2000 
Zigbee trace-related documentation is currently under development. In the meantime, you can use it as follows:

Step 1: Enable the `Zigbee Trace Enable` option in the configs.
Step 2: Call [esp_zb_set_trace_level_mask](https://github.com/espressif/esp-zboss-lib/blob/master/include/zb_osif_platform.h#L125) before `esp_zb_init` to set the level and mask. Please refer to `esp_zb_trace_level_cfg_t` for the level and [zb_trace.h](https://github.com/espressif/esp-zboss-lib/blob/master/include/zb_trace.h#L125)  for the mask. 

Based on [HA_on_off_light](https://github.com/espressif/esp-zigbee-sdk/blob/main/examples/esp_zigbee_HA_sample/HA_on_off_light/main/esp_zb_light.c#L110) example:

```
#include "zboss_api.h"

static void esp_zb_task(void *pvParameters)
{
#if CONFIG_ESP_ZB_TRACE_ENABLE
    esp_zb_set_trace_level_mask(ESP_ZB_TRACE_LEVEL4, TRACE_SUBSYSTEM_APP);
#endif


    /* initialize Zigbee stack */
    esp_zb_cfg_t zb_nwk_cfg = ESP_ZB_ZED_CONFIG();
    esp_zb_init(&zb_nwk_cfg);
    ......
    ......
}
```
The trace log is as follows:




![zigbee_trace](https://github.com/espressif/esp-zigbee-sdk/assets/39639038/a572cb1d-bf4c-4a18-8650-2e1d12435743)

**Comment by baylf2000** [comment]
@kelin6 Thank you for the information. I've been able to get that far, however once all of that information that is written to console, it needs to mean something, and without documentation a lot of it cannot be understood.

Thank you.

**Comment by kelin6** [comment]
@baylf2000 The information output to the terminal needs to be analyzed in conjunction with the specific source code. We provide Zigbee trace for the convenience of users when issues arise, allowing them to provide detailed information through the trace so that our development team can quickly pinpoint the problem.

Thank you.

**Comment by xieqinan** [comment]
@baylf2000 ,

The [debug docs](https://github.com/espressif/esp-zigbee-sdk/blob/main/docs/en/developing.rst#24-debugging) might be helpful for you.

**Comment by baylf2000** [comment]
> @baylf2000 ,
> 
> The [debug docs](https://github.com/espressif/esp-zigbee-sdk/blob/main/docs/en/developing.rst#24-debugging) might be helpful for you.

Thank you. The "debug docs" explain how to enable debugging, but don't say a single word about how to interpret the output of that debugging.

**Comment by xieqinan** [comment]
@baylf2000 ,

> but don't say a single word about how to interpret the output of that debugging.

The trace log provides a detailed process progress of the ZBOSS stack, aiding in the analysis of which layer and function might have triggered the issue. This can feedback an idea for you to locate the question and enable a quicker resolution.
Additionally, the documentation will be continuously optimized. Thank you for your suggestions.

**Comment by kelin6** [comment]
@baylf2000 

The [debugging documentation ](https://github.com/espressif/esp-zigbee-sdk/blob/main/docs/en/developing.rst#244-enable-trace-logging) been updated. If you have any further questions, please open another issue. Thank you.

**Comment by straga** [comment]
esp_zb_raw_command_handler_register for latest esp_zigbee_gateway with ot_rcp works?
devices registred in network, but raw command not print.

**Comment by straga** [comment]
esp_zb_raw_command_handler_register with esp_zigbee_gateway + ot_rcp not working.

`esp_zb_raw_command_handler_register(zb_raw_cmd_handler);`

Zigbee device registred 
![CleanShot 2024-05-25 at 09 58 57@2x](https://github.com/espressif/esp-zigbee-sdk/assets/34532/fd7e5e54-f168-4bfe-a3fd-cc3008e384b0)
 But gateway not handle on raw command.

**Comment by chshu** [comment]
There are some enhancements recently:
- some fixes in the tracing logging feature, it can output desired logs stably
- release separate debugg version libs with more logs, and produt lib for production
- mode docs for debugging purpose: https://docs.espressif.com/projects/esp-zigbee-sdk/en/latest/esp32/developing.html#debugging

For any other particular issues, feel free file new issues.
