### ISSUE TITLE
Deep sleep instead of light sleep (TZ-330)

### ISSUE THREAD

**Issue by Suxsem** [espressif/esp-zigbee-sdk#116]
Hi,
we are developing an IoT product (a garden water timer) that must be powered on batteries for a very long time. We have sorted out the mechanical part of the project by using bistable valves and a small water turbine so now the main source of power usage, especially when there is no need of water (that is most of the time during a day), is the ESP32-C6.

We need to wirelessly remote control the valve, but we don't need it to open/close immediately: the user asks to open the valve and it will open in the next 5 minutes.

This is why we thought about using Zigbee while letting the ESP32-C6 deep sleeping most of the time and wake it up every 10 minutes to check for new commands. (any other ideas are appreciated!).

We found the esp_zb_sleepy_end_device example in this repository, that uses the esp_zb_sleep_now() API to put the ESP32-C6 in light sleep. We also found that the sleep time can be tuned by settings the KEEP_ALIVE param, we plan to set it to 10 minutes (any drawback for such a long time?).

**Now the problem**: light sleep still consumes way to much power for our scenario. Is it possible to use deep sleep instead of light sleep for zigbee?

Thank you!

**Comment by kelin6** [comment]
@Suxsem The sleep duration can be adjusted by setting the `KEEP_ALIVE` parameter, as long as it stays within the specified range. Unfortunately, the Zigbee stack does not support deep sleep at the moment.

**Comment by Bosemani** [comment]
Hai @kelin6 
 I tried Light sleep example in esp32-h2, In Ideal state (sleep) it consuming 35uA. It was very High for battery operated devices.
Is Esp32-h2 zigbee support deep sleep?

**Comment by chshu** [comment]
@Suxsem @Bosemani Similar to the [Thread deep sleep](https://github.com/espressif/esp-idf/tree/master/examples/openthread/ot_sleepy_device/deep_sleep) example, it can be done in the application without changing the SDK code. We will prepare a Zigbee deep sleep example in the coming 2~3 weeks.

Note that the device will go through the rejoin process after each deep sleep, it means some additional packet interactions are necessary after each wake-up. It can be advantageous in reducing power consumption, especially when the device remains in a deep sleep state for extended periods, such as more than 30 minutes.

**Comment by Bosemani** [comment]
> @Suxsem @Bosemani Similar to the [Thread deep sleep](https://github.com/espressif/esp-idf/tree/master/examples/openthread/ot_sleepy_device/deep_sleep) example, it can be done in the application without changing the SDK code. We will prepare a Zigbee deep sleep example in the coming 2~3 weeks.
> 
> Note that the device will go through the rejoin process after each deep sleep, it means some additional packet interactions are necessary after each wake-up. It can be advantageous in reducing power consumption, especially when the device remains in a deep sleep state for extended periods, such as more than 30 minutes.

Hai @chshu 
 Thank you for your information.  From this [Comment ](https://github.com/espressif/esp-zigbee-sdk/issues/9#issuecomment-1471605491) I heard that it will take 3 seconds to report to the coordinator. New deep sleep example will overcome this problem?

**Comment by kelin6** [comment]
@Bosemani `Attribute reports take 3 seconds`  this duration can be modified by calling `esp_zb_zcl_update_reporting_info` to adjust the interval for attribute reports. This is not a sleep-related issue that needs to be addressed; it is something that Zigbee protocol stack users need to consider.

**Comment by chshu** [comment]
@Bosemani The deep sleep example is available here: https://github.com/espressif/esp-zigbee-sdk/tree/main/examples/esp_zigbee_sleep/deep_sleep, please tryout and let us know if any further questions.
