### ISSUE TITLE
Support for Multistate Value Cluster(0x0014) Zigbee (TZ-332)

### ISSUE THREAD

**Issue by Bosemani** [espressif/esp-zigbee-sdk#118]
Hai,
   I read this issue [link](https://github.com/espressif/esp-zigbee-sdk/issues/10) .
I was using espressif/esp-zigbee-lib: "~0.9.5". I think still there is no support for multistate value cluster.
We need this cluster, How can we use? Is there any alternate solution is available to use?

**Comment by xieqinan** [comment]
The feature has been supported in [ZCL Multistate](https://github.com/espressif/esp-zigbee-sdk/blob/main/components/esp-zigbee-lib/include/zcl/esp_zigbee_zcl_multistate_value.h)， please try to test it.

**Comment by xieqinan** [comment]
@Bosemani 
If the feature works fine, please close this issue.

**Comment by Bosemani** [comment]
Hai @xieqinan 
Thank you for support.
It working well! Closing this issue.
