### ISSUE TITLE
Why can I not read Temperature Attribute from this Tuya Smart Sensor? (TZ-362)

### ISSUE THREAD

**Issue by vritzka** [espressif/esp-zigbee-sdk#134]
### Question

I have the Zigbee examples running. They all work well!

But I am struggling to read a temperature sensor.

I am trying to read from a [Tuya Zigbee Mini Sensor](https://www.aliexpress.com/item/1005005454209285.html).

The sensor is discovered and successfully added to my network.

I registered the event handler `esp_zb_core_action_handler_register(zb_action_handler); `

But I cannot read the temperature from it.

Could you please give me some advice on what I am doing wrong?

This code is run every 5 seconds to read the sensor:

```
esp_zb_zcl_read_attr_cmd_t cmd_req;
cmd_req.zcl_basic_cmd.dst_addr_u.addr_short = my_tent.thermometer_short_addr;
cmd_req.zcl_basic_cmd.dst_endpoint = 1;
cmd_req.zcl_basic_cmd.src_endpoint = THERMOMETER_ENDPOINT;
cmd_req.address_mode = ESP_ZB_APS_ADDR_MODE_16_GROUP_ENDP_NOT_PRESENT;
cmd_req.clusterID = ESP_ZB_ZCL_CLUSTER_ID_TEMP_MEASUREMENT;
 uint16_t attributes[] = {ESP_ZB_ZCL_ATTR_TEMP_MEASUREMENT_VALUE_ID};
cmd_req.attr_number = sizeof(attributes) / sizeof(uint16_t);;
cmd_req.attr_field = attributes;
                                                                     
esp_zb_zcl_read_attr_cmd_req( &cmd_req); 
```

### Additional context.

I am running an  ESP32-s3 + ESP32-C6 (as RCP).

[My full code on Github](https://github.com/vritzka/TomatoTent/blob/v2/main/esp_zigbee_gateway.c)

**Comment by vritzka** [comment]
It suddenly started working. Nevermind.

**Comment by vritzka** [comment]
I am getting some output now, right after the sensor joined the network:

W (69731) ESP_ZB_GATEWAY: Receive Zigbee action
I (69731) ESP_ZB_GATEWAY: Reveived report from address(0x1df2) src endpoint(1) to dst endpoint(1) cluster(0x402)
I (69731) ESP_ZB_GATEWAY: Received report information: attribute(0x0), type(0x29), value(50)


It does that 3 or 4 times, then it stops.

This attempt at reading the sensor seems to have no effect:

```
             esp_zb_zcl_read_attr_cmd_t cmd_req;
            cmd_req.zcl_basic_cmd.dst_addr_u.addr_short = my_tent.thermometer_short_addr;
            cmd_req.zcl_basic_cmd.dst_endpoint = 1;
            cmd_req.zcl_basic_cmd.src_endpoint = THERMOMETER_ENDPOINT;
            cmd_req.address_mode = ESP_ZB_APS_ADDR_MODE_16_GROUP_ENDP_NOT_PRESENT;
            cmd_req.clusterID = ESP_ZB_ZCL_CLUSTER_ID_TEMP_MEASUREMENT;
            uint16_t attributes[] = {ESP_ZB_ZCL_ATTR_TEMP_MEASUREMENT_VALUE_ID};
            cmd_req.attr_number = sizeof(attributes) / sizeof(uint16_t);;
            cmd_req.attr_field = attributes;
                                                                     
            esp_zb_zcl_read_attr_cmd_req( &cmd_req); 
```

**Comment by xieqinan** [comment]
Hello @vritzka 

I couldn't find any group clusters. Why use groupcast to send commands?
> cmd_req.address_mode = ESP_ZB_APS_ADDR_MODE_16_GROUP_ENDP_NOT_PRESENT;

Please attempt to use `ESP_ZB_APS_ADDR_MODE_16_ENDP_PRESENT` instead.

**Comment by xieqinan** [comment]
>It does that 3 or 4 times, then it stops.

Could you attempt to use the sniffer to check the frame the gateway received? it is possiable the report frame has not been sent by the  [Tuya Zigbee Mini Sensor](https://www.aliexpress.com/item/1005005454209285.html).

**Comment by vritzka** [comment]
Thank you @xieqinan,

its partly working.

The device reports a value.

It does it about 10 times, then stops.

I don't have sniffer at hand, will get one.
