### ISSUE TITLE
Add sequence number for the read/write request command attribute (TZ-365)

### ISSUE THREAD

**Issue by diazmanuel** [espressif/esp-zigbee-sdk#135]
### Is your feature request related to a problem?

I would like to be able to identify and map the request (read/write) with its response without having to manually filter the address and cluster, according to the Zigbee 3.0 standard documentation there is a sequence number that identifies this.

### Describe the solution you'd like.

I would like the write and read functions esp_zb_zcl_read_attr_cmd_req and esp_zb_zcl_write_attr_cmd_req to return a uint8_t with the sequence number and that in the response structure (esp_zb_zcl_cmd_read_attr_resp_message_t and esp_zb_zcl_cmd_write_attr_resp_ message_t or simply in esp_zb_zcl_cmd_info_t) said sequence number appears to be able to perform the mach from this number

**Comment by xieqinan** [comment]
Hello @diazmanuel ,

I'm concerned that the feature might not be added in the recent version. However, it will be taken into consideration for inclusion in esp-zigbee-lib v1.1.0. Here's why:

Firstly, the esp_zigbee_sdk already provides ample information for users to ensure their requests match the responses. The significance of the transport sequence number is limited.

Secondly, the Zigbee stack guarantees transport sequence number matching, so users don't need to worry about mismatching issues.
