### ISSUE TITLE
Please help me understand the meaning of some return values (TZ-396)

### ISSUE THREAD

**Issue by teleger** [espressif/esp-zigbee-sdk#144]
### Is your feature request related to a problem?

static esp_err_t zb_action_handler(esp_zb_core_action_callback_id_t callback_id, const void *message)
{
    esp_err_t ret = ESP_OK;
    switch (callback_id) {
    case ESP_ZB_CORE_SET_ATTR_VALUE_CB_ID:
        ret = zb_attribute_handler((esp_zb_zcl_set_attr_value_message_t *)message);
        break;
    case ESP_ZB_CORE_CMD_REPORT_CONFIG_RESP_CB_ID:
        ret = zb_report_config_resp_handler((esp_zb_zcl_cmd_config_report_resp_message_t*)message);
        break;
    case ESP_ZB_CORE_CMD_READ_ATTR_RESP_CB_ID:
        ret = zb_read_attr_resp_handler((esp_zb_zcl_cmd_read_attr_resp_message_t *)message);
        break;
    default:
        ESP_LOGW(TAG, "Receive Zigbee action(0x%x) callback", callback_id);
        break;
    }
    return ret;
}

static esp_err_t zb_report_config_resp_handler(esp_zb_zcl_cmd_config_report_resp_message_t* message){
    esp_err_t ret = ESP_OK;
    ESP_LOGI(TAG, "Received message about config resp, from: endpoint(%d), cluster(0x%x), status(%d)", message->info.dst_endpoint, message->info.cluster,
             message->variables->status);
    ESP_LOGI(TAG, "direction (%d)",message->variables->direction);
    ESP_LOGI(TAG, "attribute_id (%d)",message->variables->attribute_id);
    return ret;
}

my Terminal output:

I (18585) ESP_ZB_GATEWAY: Received message about config resp, from: endpoint(5), cluster(0x402), status(0)
I (18585) ESP_ZB_GATEWAY: direction (108)
I (18585) ESP_ZB_GATEWAY: attribute_id (65535)

### Describe the solution you'd like.

status is 0, doesn't that mean success?
I don't particularly understand what 108 represents, I can only check the value in the SDK,
maybe it can only be 0 or 1, I can understand 65535 represents invalid,
is there any documentation to guide me how to modify?

**Comment by xieqinan** [comment]
@teleger ,

Please refer to the document for [information on ZCL commands](https://docs.espressif.com/projects/esp-zigbee-sdk/en/latest/esp32/api-reference/zcl/esp_zigbee_zcl_command.html#structesp__zb__zcl__cmd__info__s).

**Comment by teleger** [comment]
> @teleger ,
> 
> Please refer to the document for [information on ZCL commands](https://docs.espressif.com/projects/esp-zigbee-sdk/en/latest/esp32/api-reference/zcl/esp_zigbee_zcl_command.html#structesp__zb__zcl__cmd__info__s).

please tell me, version 1.0.3 new  api: esp_zb_zcl_start_attr_reporting,   

What does this function mean, turn on the report function? Also, I have an error calling this function, which is a non-zero value, it is 261, how should I understand it, thank you, I need your help

**Comment by xieqinan** [comment]
@teleger ,

The new APIs `esp_zb_zcl_start_attr_reporting()` and `esp_zb_zcl_start_attr_reporting()` provide an interface for attributes with reporting capabilities and fulfill the reporting requirement by initiating and halting reporting.

> have an error calling this function, which is a non-zero value, it is 261

Regarding the non-zero value you mentioned, is it the return value? The return value type is `esp_err_t`, and the value 261 corresponds to `Not found`. For further details, you can refer to [esp-err.h](https://github.com/espressif/esp-idf/blob/master/components/esp_common/include/esp_err.h#L29C24-L29C24).
