### ISSUE TITLE
Not able to receive correct destination endpoint ID while receiving door lock/unlock command on door lock server cluster. (TZ-412)

### ISSUE THREAD

**Issue by mallaprashant** [espressif/esp-zigbee-sdk#150]
### Answers checklist.

- [X] I have read the documentation [ESP Zigbee SDK Programming Guide](https://docs.espressif.com/projects/esp-zigbee-sdk) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) and ESP Zigbee libs ([esp-zboss-lib](https://components.espressif.com/components/espressif/esp-zboss-lib) and [esp-zigbee-lib](https://components.espressif.com/components/espressif/esp-zigbee-lib)) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

5.1.1

### esp-zigbee-lib version.

1.0.3

### esp-zboss-lib version.

1.0.2

### Espressif SoC revision.

ESP32-C6

### What is the expected behavior?

I'm expecting to receive proper destination Endpoint ID while receiving the door lock/unlock command on doorlock server cluster.

### What is the actual behavior?

Instead of receiving actual destination Endpoint ID, I'm receiving Endpoint ID as zero (message->info.dst_endpoint = 0)

### Steps to reproduce.

When handling door lock and unlock commands within the callback identified as `ESP_ZB_CORE_DOOR_LOCK_LOCK_DOOR_CB_ID`

static esp_err_t esp_zb_door_lock_cmd_handler(const esp_zb_zcl_door_lock_lock_door_message_t *message)
{
              ESP_RETURN_ON_FALSE(message, ESP_FAIL, TAG, "Empty message");
              ESP_RETURN_ON_FALSE(message->info.status == ESP_ZB_ZCL_STATUS_SUCCESS, ESP_ERR_INVALID_ARG, TAG, "Received 
              message: error status(%d)", message->info.status);
             ESP_LOGI(TAG, "Received message: endpoint(%d), cluster(0x%x)", message->info.dst_endpoint, message->info.cluster);
             return ESP_OK;
}

**Comment by xieqinan** [comment]
@mallaprashant ,

Thank you for the reminder. We will address it as soon as possible.
