### ISSUE TITLE
Lqi value and neighbor table will not updated (TZ-466)

### ISSUE THREAD

**Issue by BaWe155** [espressif/esp-zigbee-sdk#167]
### Is your feature request related to a problem?

Hello,

I use the HA_color_dimmable_light, when I send a LQI request to node/router I get a neighbour table with three neighbours but it seems that the table would not be updated, LQI is always 32 also by a power cycle

**Comment by BaWe155** [comment]
Question: how many times or when will the neighbour table be refreshed? What I see now, only after joining a network after a factory reset. Not with

**Comment by xieqinan** [comment]
The LQI value is updated in the device's neighbor table whenever it receives a frame from the neighboring device. However, the sensitivity of the LQI metric is not very high.

**Comment by BaWe155** [comment]
@xieqinan, update of the table(making a new table) searching again for best neighbours to get the best route.
I see some neighbours they are not neighbour anymore, I change the router position in the warehouse to test.

**Comment by BaWe155** [comment]
> The LQI value is updated in the device's neighbor table whenever it receives a frame from the neighboring device. However, the sensitivity of the LQI metric is not very high.

Can you explane better: However, the sensitivity of the LQI metric is not very high.

**Comment by BaWe155** [comment]
> @xieqinan, I mean update of the table(making a new table) searching again for best neighbours to get the best route. I see some neighbours they are not neighbour anymore, I change the router position in the warehouse to test.

@xieqinan any info about when a node search for new or better neighbours? And update the hall table and not only the LQI

**Comment by xieqinan** [comment]
@BaWe155 ，

The stack will adaptively maintain and update the neighbor table based on the network topology and device communication, requiring no intervention from the application.

**Comment by BaWe155** [comment]
> @BaWe155 ，
> 
> The stack will adaptively maintain and update the neighbor table based on the network topology and device communication, requiring no intervention from the application.

@xieqinan thank you for the quick reply, what I see in the field is that table with neighbours only made once (after a factory reset)
Is there a command or can you make it that refresh the table (search for new or better neighbours)

**Comment by xieqinan** [comment]
> what I see in the field is that table with neighbours only made once

No, it is a dynamic table that changes based on the network topology.

> Is there a command or can you make it that refresh the table (search for new or better neighbours) Also I see only 3 neighbours in the table can the table increase to for example 5 neighbours?

Have you tried adding more devices to the network? The neighbor table size is determined by `esp_zb_overall_network_size_set()`, with a default value of 64. I recommend conducting further tests for this issue.

**Comment by BaWe155** [comment]
> > what I see in the field is that table with neighbours only made once
> 
> No, it is a dynamic table that changes based on the network topology.
> 
> > Is there a command or can you make it that refresh the table (search for new or better neighbours) Also I see only 3 neighbours in the table can the table increase to for example 5 neighbours?
> 
> Have you tried adding more devices to the network? The neighbor table size is determined by `esp_zb_overall_network_size_set()`, with a default value of 64. I recommend conducting further tests for this issue.

@xieqinan I don’t think it is dynamic, can you test and check it?
Now we have 30 routers in a network, with a LQI request only I get three neigbours, overall network size is set to 100

**Comment by xieqinan** [comment]
Could you please check the [neighbor_table_entries](https://github.com/espressif/esp-zigbee-sdk/blob/608f7c0b1f57d825d0af0ce471e30d53d0d02b2a/components/esp-zigbee-lib/include/zdo/esp_zigbee_zdo_command.h#L382) parameter of `esp_zb_zdo_mgmt_lqi_rsp_t`, which indicates the total number of entries in the neighbor table? If the sum of `start_index` and `neighbor_table_list_count` is less than this value, please issue another request starting from the updated `start_index` to retrieve the remaining neighbor information.
