### ISSUE TITLE
esp_zb_zcl_set_attribute_val function not working with SONOFF gateway but working with Tuya gateway. (TZ-488)

### ISSUE THREAD

**Issue by mundevx** [espressif/esp-zigbee-sdk#180]
### Question

As if i press button from my espressif board (Router mode and Server Cluster) and call the following function, 
esp_zb_zcl_status_t status = esp_zb_zcl_set_attribute_val(
	g_device_ctx[index].on_off_light.endpoint,
	ESP_ZB_ZCL_CLUSTER_ID_ON_OFF,
	ESP_ZB_ZCL_CLUSTER_SERVER_ROLE,
	ESP_ZB_ZCL_ATTR_ON_OFF_ON_OFF_ID,
	(bool*)&light_state[index],
	false
);

then this is working with Tuya gateway (Switch toggles in app) but not working with Sonoff gateway (Switch is NOT toggles in app).
Can anybody help me.

**Comment by chshu** [comment]
@mundevx please check with gateway vendor for this issue.
