### ISSUE TITLE
How to create custom cluster ID (TZ-514)

### ISSUE THREAD

**Issue by tengulak** [espressif/esp-zigbee-sdk#192]
### Is your feature request related to a problem?

i try to create my own custom cluster id, but there is only one function "esp_zb_zcl_attr_list_create" which supports only defined clusters. Is there any function ?

**Comment by xieqinan** [comment]
Hello @tengulak ，

The custom cluster ID in `esp-zigbee-sdk` is required to be greater than 0xFC00. You can use the function `esp_zb_zcl_attr_list_create(custom_cluster_id)` to create a custom attribute list.

**Comment by chshu** [comment]
@tengulak Please reopen if any follow up questions.
