### ISSUE TITLE
ZCL attribute reporting by trigger (TZ-50)

### ISSUE THREAD

**Issue by u236** [espressif/esp-zigbee-sdk#2]
Hello! I've successfully build `HA_light_on_off` example with some additions, such a led state control with button, and it works good. Attribute reporting, configured via "configure reporting" global command, works too, but i can't understand, how to trigger device to report led state attribute when it's changed with button?

**Comment by likunqiao097304** [comment]
@u236 Good to hear you are running successfully. According to the specs, if you set the min_interval to 0, it should report immediately when reportable value change. However, there is a issue that it couldn't report as soon as possible. We are working on that to fix it.

**Comment by u236** [comment]
I now, how reporting works, but i don't understand how to tell zigbee stack about attrubute was changed
