### ISSUE TITLE
How to send "On With Timed Off" command? (TZ-554)

### ISSUE THREAD

**Issue by g-chevalier** [espressif/esp-zigbee-sdk#209]
### Question

Hi,

I would like to send an On/off command using the "On With Timed Off" variant (0x42).
Up to now, I was able to declare the 2 new ESP_ZB_ZCL_ATTR_ON_OFF_ON_TIME and ESP_ZB_ZCL_ATTR_ON_OFF_OFF_WAIT_TIME attributes to the On/Off cluster.
My code is working with the Toggle command, I can control a Zigbee lamp using esp_zb_zcl_on_off_cmd_req()

But I cannot figure out how to send the "On With Timed Off".
Simply using the below code is not working.
```
esp_zb_zcl_on_off_cmd_t cmd_req;
cmd_req.zcl_basic_cmd.dst_addr_u.addr_short = 0x4EC4; // Constant to test...
cmd_req.zcl_basic_cmd.dst_endpoint = 1;
cmd_req.zcl_basic_cmd.src_endpoint = 1;
cmd_req.address_mode = ESP_ZB_APS_ADDR_MODE_16_ENDP_PRESENT;
//cmd_req.on_off_cmd_id = ESP_ZB_ZCL_CMD_ON_OFF_TOGGLE_ID; This is working well
cmd_req.on_off_cmd_id = ESP_ZB_ZCL_CMD_ON_OFF_ON_WITH_TIMED_OFF_ID;
// Attributes bellow created using esp_zb_on_off_cluster_add_attr(esp_zb_on_off_cluster, ESP_ZB_ZCL_ATTR_ON_OFF_ON_TIME, &onoff_on_time);
onoff_on_time = 10;
onoff_of_wait_time = 0;
esp_zb_zcl_on_off_cmd_req(&cmd_req);
```

Is this currently supported or is there something missing in esp_zigbee_zcl_command.h?

**Comment by xieqinan** [comment]
Hello,

The issue has been fixed in [esp-zigbee-sdk v1.1.2](https://github.com/espressif/esp-zigbee-sdk).
