### ISSUE TITLE
Coordinator sends "leave" command after the association (TZ-111)

### ISSUE THREAD

**Issue by Ravenen** [espressif/esp-zigbee-sdk#21]
I am using `esp-zigbee-gateway` example on the ESP32C6. 
I added some communications after the end device association: ask active endpoints list, ask simple descriptor on each endpoint.
After that, the `ESP_ZB_ZDO_SIGNAL_LEAVE_INDICATION` signal is received, and I see in the WireShark that coordinator sends the `leave` command to that device.
![image](https://github.com/espressif/esp-zigbee-sdk/assets/57559975/2ce59a90-90e7-4754-8ceb-fb11a81af1d0)
![image](https://github.com/espressif/esp-zigbee-sdk/assets/57559975/4419de19-3506-4304-b72d-3cdcc1796544)
![image](https://github.com/espressif/esp-zigbee-sdk/assets/57559975/ae089ab5-4afa-4be0-a3c4-ada1eef772a4)
![image](https://github.com/espressif/esp-zigbee-sdk/assets/57559975/b1dc1355-8e9c-4565-9d0a-df453db62deb)

[zigbee sdk pairing pcapng.zip](https://github.com/espressif/esp-zigbee-sdk/files/11442216/zigbee.sdk.pairing.pcapng.zip)

**Comment by likunqiao097304** [comment]
It seems like coordinator is trying to send the nwk key(No.14) but no further action from end-device to request  trust center link key.  Is end-device also our Zigbee stack or our board? Also by default we disable using install code policy to do the network commissioning, so please check both size have the same security mechanism.

**Comment by Ravenen** [comment]
Thank you for your response!
End Device is a Sonoff temperature sensor. I didn't change any security configs in the example. So, again, what are the recommendations to fix that? Or should I give some more information?

**Comment by likunqiao097304** [comment]
Does this Sonoff temperature sensor use Zigbee 3.0 standard way to do the commission? Like it has install code and MAC on the label. I'd like to know how is process from your side to let your sensor join the network. Have you tried to join other Zigbee coordinator successfully?

From the log you provided, our Zigbee coordinator did send the network key successfully (a351a85....). And later encrypted ZDO active endpoint, simple descriptor request, your sensor did decrypte correctly with response. However, end-device(sensor) didn't do response/action with the network key. 

Here is a picture that we see as successfully join. Highlight them in blue:
![image](https://github.com/espressif/esp-zigbee-sdk/assets/3393154/cb0ddb4d-26fa-4a92-9ff2-7fa6ae1276cf)

**Comment by Ravenen** [comment]
Yes, I have tried to join it to other coordinator with CC ZigBee stick and ZigBee2Mqtt software. I also have the association process captured with the WireShark. There is also no response to the network key, but the coordinator keeps the device in the network.  

[zigbee switch pairing.zip](https://github.com/espressif/esp-zigbee-sdk/files/11464739/zigbee.switch.pairing.zip)

![image](https://github.com/espressif/esp-zigbee-sdk/assets/57559975/f309b128-b695-47cd-b8cf-f808a737fff2)
![image](https://github.com/espressif/esp-zigbee-sdk/assets/57559975/476dc8b1-5e67-4514-a14f-b22f59efef31)
![image](https://github.com/espressif/esp-zigbee-sdk/assets/57559975/baed88eb-535c-4e6c-af5e-7aa02d53567a)

**Comment by Ravenen** [comment]
And yes, the manual of the device does say that it supports ZigBee 3.0.  
![PXL_20230512_135839185~2](https://github.com/espressif/esp-zigbee-sdk/assets/57559975/81768ba7-3ad0-4098-b804-adad27ffd3da)

**Comment by Ravenen** [comment]
So... Any suggestions here? What can I possibly do to help with my issue?

**Comment by xieqinan** [comment]
Hi Ravenen,
The problem described above can potentially be resolved by disabling the `bdbTrustCenterRequireKeyExchange` MACRO in the Zigbee Gateway. This solution is outlined in the Zigbee BDB specification provided below. An API for configuring the MACRO will be made available as soon as possible in ESP-ZigBee-SDK.
![MicrosoftTeams-image](https://github.com/espressif/esp-zigbee-sdk/assets/49604229/1de3a816-d2c4-4ddc-9bcc-4849c2273018)

The End Device will be allowed to join the Zigbee network without the requirement of exchanging a link key, if the Zigbee Gateway disables `bdbTrustCenterRequireKeyExchange` option. However, it is important to note that this approach is considered unsafe for the Zigbee network.

**Comment by chshu** [comment]
@Ravenen The issue should be resolved by disable the option: https://github.com/espressif/esp-zigbee-sdk/blob/main/components/esp-zigbee-lib/include/esp_zigbee_secur.h#L133
