### ISSUE TITLE
Add support for particulate matter cluster PM1.0, PM4.0 and PM10. (TZ-558)

### ISSUE THREAD

**Issue by deviashin** [espressif/esp-zigbee-sdk#211]
Hello!
Should we expect other types of particulate matter other than esp_zigbee_zcl_pm2_5_measurement.h?
My project uses Honeywell's HPMA115C0-004 sensor which provides data such as PM1.0, PM2.5, PM4.0 and PM10.

**Comment by xieqinan** [comment]
@deviashin ,

The terms "PM1.0, PM2.5, PM4.0, and PM10" do not appear to be defined in the specification. If necessary, you can use a custom cluster to support these measurements.

**Comment by deviashin** [comment]
I should have paid attention to this before making the request. I agree, there are no such clusters in the ZCL standard. Same as AQI. Well, let's hope they add it someday.
