### ISSUE TITLE
ESP32S3 and H2 router board (TZ-574)

### ISSUE THREAD

**Issue by djorr5** [espressif/esp-zigbee-sdk#216]
### Question

I am running my code on the router board which contains an S3 and a H2. My code is based on the gateway example and originally worked fine. However I have since added more and more code to the S3. Some MQTT as well as some additions to the zigbee code. However it now gives me an error.
```c++
I (17122) ZBOSS: macsplit/zb_macsplit_host.c:171   >radio boot indication
I (17122) ZBOSS: macsplit/zb_macsplit_host.c:173   boot indication
I (17132) ZBOSS: macsplit/zb_macsplit_host.c:213   Unexpected zb_mlme_dev_reset_conf - seems, device is asserted
I (17142) ZBOSS: common/zb_error_indication.c:93   >> zb_error_raise severity 254, err_code -2561
D (17152) mqtt_client: esp_mqtt_handle_transport_read_error: transport_read(): call timed out before data was ready!
I (17152) ZBOSS: common/zb_error_indication.c:59   Error is not handled: severity 254, err_code -2561
I (17172) ZBOSS: common/zb_debug.c:64   Assertion failed /home/xieqinan/ESP/esp-zboss/components/zboss_stack/zboss/common/zb_error_indication.c:81
``` 
My question is can I keep adding Zigbee code on the S3 and it should just get passed through to the H2? I saw in another issue ([https://github.com/espressif/esp-zigbee-sdk/issues/138](url) you instructed the OP to only use the Gateway example, hence why I want to know if I start with the Gateway example I am ok to keep adding code to it.

**Comment by xieqinan** [comment]
@djorr5 ,

This issue will be addressed in the release scheduled for later this week.
