### ISSUE TITLE
Custom Cluster write Callback (TZ-114)

### ISSUE THREAD

**Issue by diazmanuel** [espressif/esp-zigbee-sdk#22]
Hello! 

I am trying to add a callback when an attribute of a custom cluster is modified
the custom cluster is created correctly and I can modify its attributes with another zigbee device but the callback is not called and returns the following message:

ESP_ZIGBEE_CORE: cluster ID:65534, attribute ID:0 is currently not supported for updating!

iam ussing the master sdk.
This means that the sdk does not support the callback for custom clusters, is there a solution to this?

I am registering the callback as follows:

void attr_cb(uint8_t status, uint8_t endpoint, uint16_t cluster_id, uint16_t attr_id, void *value)
{
    ESP_LOGI(TAG,"Callback");
}
static void esp_zb_task(void *pvParameters)
{
    esp_zb_cfg_t zb_nwk_cfg = ESP_ZB_ZED_CONFIG();
    esp_zb_init(&zb_nwk_cfg);

    uint32_t FFFE_flag=5;
    uint16_t FFFE_away;
    uint16_t FFFE_hum;
    uint16_t FFFE_bat;
    uint8_t FFFE_crono[200];

    esp_zb_attribute_list_t *FFFE = esp_zb_zcl_attr_list_create(0xFFFE);
    esp_zb_custom_cluster_add_custom_attr(FFFE, 0x00, 0x23, 0x07,&FFFE_flag);
    esp_zb_custom_cluster_add_custom_attr(FFFE, 0x01, 0x29, 0x07,&FFFE_away);
    esp_zb_custom_cluster_add_custom_attr(FFFE, 0x02, 0x29, 0x05,&FFFE_hum);
    esp_zb_custom_cluster_add_custom_attr(FFFE, 0x03, 0x29, 0x05,&FFFE_bat);
    esp_zb_custom_cluster_add_custom_attr(FFFE, 0x04, 0x42, 0x06,FFFE_crono);

    esp_zb_cluster_list_t *esp_zb_cluster_list = esp_zb_zcl_cluster_list_create();
    esp_zb_cluster_list_add_custom_cluster(esp_zb_cluster_list, FFFE, ESP_ZB_ZCL_CLUSTER_SERVER_ROLE);
    esp_zb_device_add_set_attr_value_cb(attr_cb);

    esp_zb_set_primary_network_channel_set(ESP_ZB_PRIMARY_CHANNEL_MASK);
    ESP_ERROR_CHECK(esp_zb_start(false));
    esp_zb_main_loop_iteration();
}

**Comment by likunqiao097304** [comment]
@diazmanuel The attribute callback are now only supported changes from  ON/OFF, LEVEL, COLOR attribute change, not the customized attribute callback.  For the customized cluster related, we supported custom cluster command callback, read attribute callback. We will support your need in the future release.

**Comment by diazmanuel** [comment]
> @diazmanuel The attribute callback are now only supported changes from ON/OFF, LEVEL, COLOR attribute change, not the customized attribute callback. For the customized cluster related, we supported custom cluster command callback, read attribute callback. We will support your need in the future release.

Thanks for the answer. I would like to know when you plan to support this functionality since it seems to be something simple, the sdk already correctly identifies the cluster and the attribute, it also allows you to modify it and the warning that it launches is executed when the attribute is edited, so the only thing that would be missing is to enable the call to the callback function

**Comment by chshu** [comment]
@diazmanuel The issue has been fixed in latest main branch, please try it out, thanks for reporting the issue.

**Comment by abdulrehmanee12** [comment]
hi @diazmanuel for a quick fix you need to use  esp_zb_add_custom_cluster_command_cb(HA_ESP_LIGHT_ENDPOINT, ESP_ZB_ZCL_CLUSTER_ID_CUSTOM, NULL);  in your example code to register custom cluster id as in our internal implementation we are currently using custom_cluster_command_cb to register custom cluster id . Later we can workaround to change it.

**Comment by likunqiao097304** [comment]
@diazmanuel Hi, the latest release has been fixed the recently error you faced, please try it out.

**Comment by diazmanuel** [comment]
@likunqiao097304 Perfect, now it works correctly

**Comment by abdulrehmanee12** [comment]
@diazmanuel Currently , only u8,u16,u32 data types are supported for custom cluster write attr callback. We will add the signed data types in next release.

**Comment by Bosemani** [comment]
Hai @diazmanuel 
 I'm also getting same error like yours "_W (236902) ESP_ZIGBEE_CORE: cluster ID:65534, attribute ID:0 is currently not supported for updating!"_ 
Which version this bug is rectified?
