### ISSUE TITLE
zone_status attribute of cluster iasZone should be of type uint16_t, not uint8_t (TZ-583)

### ISSUE THREAD

**Issue by Suxsem** [espressif/esp-zigbee-sdk#221]
### Answers checklist.

- [X] I have read the documentation [ESP Zigbee SDK Programming Guide](https://docs.espressif.com/projects/esp-zigbee-sdk) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) and ESP Zigbee libs ([esp-zboss-lib](https://components.espressif.com/components/espressif/esp-zboss-lib) and [esp-zigbee-lib](https://components.espressif.com/components/espressif/esp-zigbee-lib)) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

release/5.2

### esp-zigbee-lib version.

1.0.8

### esp-zboss-lib version.

1.0.8

### Espressif SoC revision.

ESP32-C6

### What is the expected behavior?

zone_status attribute of cluster iasZone should be of type uint16_t

![image](https://github.com/espressif/esp-zigbee-sdk/assets/830773/20e1fe94-89df-4099-9813-2859350b3097)

### What is the actual behavior?

it's declared as uint8_t

![image](https://github.com/espressif/esp-zigbee-sdk/assets/830773/610a4da6-f152-46b5-9702-191667f746c3)

### Steps to reproduce.

as described

**Comment by xieqinan** [comment]
@Suxsem ,

Thanks for your reminder, it will be fixed within this week.
