### ISSUE TITLE
Power reduction of a router (TZ-592)

### ISSUE THREAD

**Issue by BaWe155** [espressif/esp-zigbee-sdk#227]
### Question

Hello,

I’m wondering if is possible to reduce power consume of a router or is reduction of Tx power the only option? 

Kind regards
Bas

**Comment by chshu** [comment]
The router should be RX always on, so the RX power consumption is the base line for a router device. Reduce Tx power only helps to save some power for transmission.

**Comment by chshu** [comment]
The router device can't sleep, otherwise it will cause connectivity issues. Only Sleepy end device could enable sleep mode.

Please stay tuned for our new SoCs release which could do better on power consumption.

**Comment by BaWe155** [comment]
Thank you, do you have a report with Zigbee router power consume?

Grtz
Bas

**Comment by chshu** [comment]
You may refer to the `4.6 Current Consumption` section from C6 datasheet here: https://www.espressif.com/sites/default/files/documentation/esp32-c6_datasheet_en.pdf.

The router power baseline is 802.15.4 RX mode, and the peak is the Tx mode.

**Comment by BaWe155** [comment]
Thank you for the info, I had seen it. Now I understand it better

Van: Shu Chen ***@***.***>
Verzonden: donderdag 25 januari 2024 10:44
Aan: espressif/esp-zigbee-sdk ***@***.***>
CC: Liftsens | Bas Weppel ***@***.***>; Author ***@***.***>
Onderwerp: Re: [espressif/esp-zigbee-sdk] Power reduction of a router (TZ-592) (Issue #227)


You may refer to the 4.6 Current Consumption section from C6 datasheet here: https://www.espressif.com/sites/default/files/documentation/esp32-c6_datasheet_en.pdf.

The router power baseline is 802.15.4 RX mode, and the peak is the Tx mode.

**Comment by BaWe155** [comment]
Hello,

How to set a TX power to -15dBm?  now I use      esp_zb_set_tx_power(0);

**Comment by xieqinan** [comment]
@BaWe155 ,

You  can use the `esp_zb_set_tx_power(-15)` function, it sets the TX power to -15 dBm directly. However, please note that the minimum TX power value is -15 dBm for the ESP32C6 and -24 dBm for the ESP32H2.

**Comment by BaWe155** [comment]
@xieqinan 

Thank you.
Is it possible to reduce the system clock speed of the microcontroller? and running the zigbee stack?
