### ISSUE TITLE
How can I fix 'esp_zigbee_gateway' build error on Win11 for GW_AUTO_UPDATE_RCP=1 ? (TZ-601)

### ISSUE THREAD

**Issue by kivanychev** [espressif/esp-zigbee-sdk#231]
### Question

When building the 'esp_zigbee_gateway' under Windows11 I get the following error message:

```
FAILED: esp-idf/main/CMakeFiles/rcp_image_generation 
F:/esp32/esp-zigbee-sdk/examples/esp_zigbee_gateway/build/esp-idf/main/CMakeFiles/rcp_image_generation cmd.exe /C "cd /D F:\esp32\esp-zigbee-sdk\examples\esp_zigbee_gateway\build\esp-idf\main && F:\esp32\esp-zigbee-sdk\examples\esp_zigbee_gateway\main\..\create_ota_image.py --rcp-build-dir F:/esp32/esp-zigbee-sdk/examples/esp_zigbee_gateway/../esp_zigbee_rcp/build --target-file F:/esp32/esp-zigbee-sdk/examples/esp_zigbee_gateway/build/esp-idf/main/
```

**PRECONDITIONS#1**
 1. Two PCs with Windows10 and Windows11 operating systems
 2. Each PC has the following installations:
    * Git
    * Python 3.11
    * just installed IDF 5.1.2
    * cloned zigbee-sdk
    * has already successfuly built RCP image in the 'zigbee-sdk/examples/esp_zigbee_rcp'

**STEPS#1**
    
 1 - For the Gateway code example "zigbee-sdk/examples/esp_zigbee_gateway"
    Choose target ESP32-S3
    From 'menuconfig' the "Update RCP automatocally" choose to 'NOT set'
    
 2 - Build the code
    
**RESULT#1**
 The code is succeccfuly built on Windows10 and Windows11 PCs
 The resulting code works fine in ESP32S3
 

**PRECONDITIONS#2**
 Using the'menuconfig' choose the flag "Update RCP automatocally"  (CONFIG_ZIGBEE_GW_AUTO_UPDATE_RCP --> true)
 
**STEPS#2**
 1 - Build the code for Windows10
 2 - Build the code for Windows11
 
**RESULT#2**
 1 - On Windows10 PC the code Succeccfuly build
 2 - On Windows11 PC the code Fails with the following error message:

FAILED: esp-idf/main/CMakeFiles/rcp_image_generation F:/esp32/esp-zigbee-sdk/examples/esp_zigbee_gateway/build/esp-idf/main/CMakeFiles/rcp_image_generation
cmd.exe /C "cd /D F:\esp32\esp-zigbee-sdk\examples\esp_zigbee_gateway\build\esp-idf\main && F:\esp32\esp-zigbee-sdk\examples\esp_zigbee_gateway\main\..\create_ota_image.py --rcp-build-dir F:/esp32/esp-zigbee-sdk/examples/esp_zigbee_gateway/../esp_zigbee_rcp/build --target-file F:/esp32/esp-zigbee-sdk/examples/esp_zigbee_gateway/build/esp-idf/main/spiffs_image/ot_rcp_0/rcp_image"

**ANALYSIS**
* For some reason '`create_ota_image.py`' failed to run and the '`esp_zigbee_gateway/build/esp-idf/main/spiffs_image/ot_rcp_0/rcp_image`' was not created.
* All other .py scripts can be run without additional 'python'
 
* I fixed the problem by adding 'python' to the command in the 'esp_zigbee_gateway\main\CMakeLists.txt'
  Was:  
`    COMMAND ${CMAKE_CURRENT_SOURCE_DIR}/../create_ota_image.py`
  
  Modified:
`    COMMAND python ${CMAKE_CURRENT_SOURCE_DIR}/../create_ota_image.py`

**QUESTION:**
How can I fix this issue for Windows11 PC without adding 'python' to the command?

**Comment by chshu** [comment]
Adding `python` is the correct solution, we will fix this in soon.
