### ISSUE TITLE
Router can't join a network at a distance of +/- 20meters (TZ-610)

### ISSUE THREAD

**Issue by BaWe155** [espressif/esp-zigbee-sdk#235]
### Question

How to get a router ESP32C6 with TX power value 0 (dBm?) joined at a distance of 20 meter (LQI is than 10) can I do something with the link cost? 

### Additional context.

After factory reset and a first join at 2meter (20 meter is not possible), the router can reach 20 meters (LQI=10)

**Comment by BaWe155** [comment]
![Join and hopes](https://github.com/espressif/esp-zigbee-sdk/assets/87778249/a9241799-f6de-4eea-a154-085a9b3a533a)
c
I have tested the following situation, see figure:

A router would only join after a factory reset at position A, not at B or C and would not make hopes.
After a factory reset and a join at position A, I move a router to position B, it will connect with the network. At position C a router will not join after factory reset, it need first a join at position A after that moving the router to position C, it will make a connection with a hope via B

**Comment by chshu** [comment]
@BaWe155 Did you do the test with 0 dBm txpower? I think 0 dBm is too low for 40 meters distance, could you increase the txpower by [esp_zb_set_tx_power](https://github.com/espressif/esp-zigbee-sdk/blob/main/components/esp-zigbee-lib/include/esp_zigbee_core.h#L473) API, and rerun the tests?

**Comment by BaWe155** [comment]
> @BaWe155 Did you do the test with 0 dBm txpower? I think 0 dBm is too low for 40 meters distance, could you increase the txpower by [esp_zb_set_tx_power](https://github.com/espressif/esp-zigbee-sdk/blob/main/components/esp-zigbee-lib/include/esp_zigbee_core.h#L473) API, and rerun the tests?

@chshu 
I think for now the TX power is not a problem, the routers will make only make a join at small range of the coordinator (with a factory reset) after that I can reach a range of +/- 20 meter with 0dBm
Can a router C join a network via a hop (B) after a factory reset, is the stack tested for this?

**Comment by chshu** [comment]
> Can a router C join a network via a hop (B) after a factory reset, is the stack tested for this?

Yes, it works. But if the RSSI / LQI is too low, the device will consider the link is too bad, and refuse to join the network via this parent. The LQI threshold is 32 (RSSI is around -74 dBm) in current SDK.

**Comment by BaWe155** [comment]
> > Can a router C join a network via a hop (B) after a factory reset, is the stack tested for this?
> 
> Yes, it works. But if the RSSI / LQI is too low, the device will consider the link is too bad, and refuse to join the network via this parent. The LQI threshold is 32 (RSSI is around -74 dBm) in current SDK.

@chshu Thank you for the quick reply, Is it possible to change the threshold?

**Comment by chshu** [comment]
It can't be changed with current SDK, but we can make it configurable in future release. However lower threshold may cause stability issues with high packet loss rate.

**Comment by BaWe155** [comment]
> It can't be changed with current SDK, but we can make it configurable in future release. However lower threshold may cause stability issues with high packet loss rate.

Are you sure that a factory new router can join the network trough router at position B (join via other routers not only via the coordinator)? when I place a factory new router 1 meter from B, it would not join the network (LQI is more than 32)

**Comment by xieqinan** [comment]
Hello @BaWe155,

> Are you sure that a factory new router can join the network trough router at position B (join via other routers not only via the coordinator)? when I place a factory new router 1 meter from B, it would not join the network (LQI is more than 32)

In a centralized network, a device intending to join a network created by the coordinator typically needs to be able to communicate with the Trust Center directly. The routers in the centralized network should not be responsible for managing the network key exchange process.

![image](https://github.com/espressif/esp-zigbee-sdk/assets/49604229/5b35330a-2900-4fdc-aedf-a35e85971b38)


Therefore,I believe the factory new router can not join the network trough router at position B.

**Comment by BaWe155** [comment]
@xieqinan thank you for the info.

Is my conclusion right? If there is meshnetwork and I will join a new router nearby position C (The range to the coordinator/(trust center) is too far/large, The new router can’t join in the network?

**Comment by xieqinan** [comment]
@BaWe155 ,

Yes, according to the Zigbee BDB specification, your conclusion is correct. The behavior of the ESP-Zigbee-SDK on the ESP32H2 is also correct.

**Comment by Hedda** [comment]
> How to get a router ESP32C6 with TX power value 0 (dBm?) joined at a distance of 20 meter (LQI is than 10) can I do something with the link cost?

> I think for now the TX power is not a problem, the routers will make only a join at small range of the coordinator (with a factory reset) after that I can reach a range of +/- 20 meter with 0dBm

FYI, unless you are talking about line-of-sight outdoors with no obstacles or walls/ceilings/floors then that is how Zigbee normally works. Indoors with normal obstacles and walls/ceilings/floors then standard Zigbee device range is usually around 5 meters.

2.4GHz based Zigbee devices are low-power devices and the high-frequency used makes them all have short range and poor radio propagation (building material penetration) so they all depend on being part of a larger and stable/reliable Zigbee network mesh with many Zigbee Router devices connected in a mesh network + on top of that Zigbee radios are also relatively speaking very susceptible to EMF/RMI/RMI interference, so highly recommend you read  these related guides and follow recommendations:

https://community.home-assistant.io/t/zigbee-networks-how-to-guide-for-avoiding-interference-and-optimize-for-getting-better-range-coverage/515752

and

https://community.home-assistant.io/t/not-many-people-know-that-a-random-collection-of-zigbee-trivia/656267

Summery; Regardless of your Zigbee device types and setup, you really need to be aware of Zigbee limitations and reliance on mesh networking and then take appropriate actions, most importantly adding many more Zigbee Router devices closer to each other to extend range/coverage and almost as important is avoiding EMF/RMI/RMI sources interference close to Zigbee radios, (especially close to the Zigbee Coordinator adapter, which is a single point of failure in an RF noisy environment so make sure get that at least 1 meter away from anything electric).

PS: Slightly off-topic but also recommend reading this -> https://community.home-assistant.io/t/zigbee-buyers-guide/654695

**Comment by xieqinan** [comment]
@BaWe155 @Hedda 

I may have made a mistake regarding the "Figure 12 – Trust Center link key exchange procedure sequence chart." I conducted a test as follows: After performing a factory reset and a join at position A, I moved a router to position B, where it successfully connected to the network. However, at position C, a router failed to join after a factory reset. However, if the factory-reset router was placed at position D can be routed through position B so that it was able to join the network.

![image](https://github.com/espressif/esp-zigbee-sdk/assets/49604229/a96e7d3a-d0cb-4e83-b0db-e329e55e1c0e)

In summary, while the stack requires an RSSI value of more than -74 during the joining network process, there seems to be no such limitation for joined devices.  Therefore, could you also attempt to place the device at position D and observe its behavior?

> In a centralized network, a device intending to join a network created by the coordinator typically needs to be able to communicate with the Trust Center directly. The routers in the centralized network should not be responsible for managing the network key exchange process.

The test verifies that it was an erroneous conclusion. Actually, the position B can indeed route the network key for devices whose RSSI from the beacon is sufficiently large.

**Comment by chshu** [comment]
> Is it possible to change the threshold?

@BaWe155 A new API is provided to change the threshold:
https://docs.espressif.com/projects/esp-zigbee-sdk/en/latest/esp32/api-reference/esp_zigbee_secur.html#_CPPv437esp_zb_secur_network_min_join_lqi_set7uint8_t, please have a try.

Please reopen if you have any follow up question on this topic.

**Comment by BaWe155** [comment]
@chshu 
Thank you I will test it

**Comment by BaWe155** [comment]
@chshu @xieqinan 

I have a question about:
void esp_zb_secur_network_min_join_lqi_set
Set the minimum LQI value for device joining the network.

Is the min LQI for a factory reset join or also for a rejoin in a network were the router already have access (try to get online again)?
Did this min LQI also have effect at the route discovery and making a neighbour table?

Have a problem with fluctuated LQI, sometimes a router is not online any more after a power cycle it will be online again.

**Comment by xieqinan** [comment]
> Is the min LQI for a factory reset join or also for a rejoin in a network were the router already have access (try to get online again)?
Did this min LQI also have effect at the route discovery and making a neighbour table?

The minimum LQI setting only takes effect during a factory reset join and does not influence the router discovery process.

**Comment by BaWe155** [comment]
@chshu @xieqinan thank you for the info.

(node is add to a network) is there a command to trigger a re-connection to a network, if auto connect not work. or how can I check if a node tries to re-connect?

**Comment by xieqinan** [comment]
If the node fails to connect to the network, the stack will trigger the `ESP_ZB_BDB_SIGNAL_DEVICE_FIRST_START` signal with a failure status. You can schedule `ESP_ZB_BDB_MODE_INITIALIZATION` to retry the connection. Please refer to the [retry mechanism](https://github.com/espressif/esp-zigbee-sdk/blob/main/examples/esp_zigbee_HA_sample/HA_on_off_light/main/esp_zb_light.c#L64).

**Comment by BaWe155** [comment]
@xieqinan @chshu Thank you for the quick reply!
Now my questions are how does the node knows there is a connection after a couple of hours/days?
Is there a mechanism that checks if the node is in the network?

What I think is this is only at a restart/power cycle:
    case ESP_ZB_BDB_SIGNAL_DEVICE_FIRST_START:
    case ESP_ZB_BDB_SIGNAL_DEVICE_REBOOT:

**Comment by xieqinan** [comment]
@Hedda 

> Is there a mechanism that checks if the node is in the network?

Understood, regarding the router, it is able to maintain a network by itself, so it should be on the network all the time once it joined. If there is no any devices around the router, the `ESP_ZB_NWK_SIGNAL_NO_ACTIVE_LINKS_LEFT` signal will be triggred to application to indiate no active links. Regarding the end device, if it can not communicate with its parents, the `ESP_ZB_BDB_SIGNAL_DEVICE_REBOOT` will be triggered to application to indicate it is not on the network.
