### ISSUE TITLE
[Feature request] increase the allowed size of the maximum and minimum interval report  (TZ-118)

### ISSUE THREAD

**Issue by diazmanuel** [espressif/esp-zigbee-sdk#24]
Hello, could you change the data type of the max interval and min interval within the report config to uin16_t as the zigbee 3.0 standard says?
![zigbee](https://github.com/espressif/esp-zigbee-sdk/assets/39015966/47f56f90-78ce-4c6a-9d68-defebe31222a)

Currently the data type is set as uint8_t 
https://docs.espressif.com/projects/esp-zigbee-sdk/en/latest/esp32/api-reference/zcl/esp_zigbee_zcl_command.html?highlight=esp_zb_zcl_config_report_cmd_req#_CPPv430esp_zb_zcl_config_report_cmd_s

**Comment by likunqiao097304** [comment]
Thanks, we will do this update

**Comment by diazmanuel** [comment]
Thanks, is there a roadmap or a log of the changes that are being implemented in each update? I would like to keep abreast of the changes that are being added.

**Comment by likunqiao097304** [comment]
@diazmanuel Currently no road map, but we have noticed this need from many users, we will add this later. Thanks for your advice
