### ISSUE TITLE
Scene table entries issues (TZ-630)

### ISSUE THREAD

**Issue by mundevx** [espressif/esp-zigbee-sdk#243]
### Question

I have zigbee 4 gang light switch with four endpoints i.e. 4 light switches in a single node. 
Also i had 3 4 gang scene switch with four switches endpoints having 3 scenes on each switch i.e. total of 12 scenes in a 4 gang scene switch. 

Total scene entries = 4 light switches X 12 scenes = 48.
But after adding 16 entries (4 scenes * 4 lights endpoints in a node = 16), i am showing you the logs

_Scene 1:
ESP_ZIGBEE_CORE: Store new scene(0x1) of group(0x1) to scenes table (Endpoint1)
ESP_ZIGBEE_CORE: Store new scene(0x1) of group(0x1) to scenes table (Endpoint2)
ESP_ZIGBEE_CORE: Store new scene(0x1) of group(0x1) to scenes table (Endpoint3)
ESP_ZIGBEE_CORE: Store new scene(0x1) of group(0x1) to scenes table (Endpoint4)
Scene 2:
ESP_ZIGBEE_CORE: Store new scene(0x2) of group(0x2) to scenes table (Endpoint1)
ESP_ZIGBEE_CORE: Store new scene(0x2) of group(0x2) to scenes table (Endpoint2)
ESP_ZIGBEE_CORE: Store new scene(0x2) of group(0x2) to scenes table (Endpoint3)
ESP_ZIGBEE_CORE: Store new scene(0x2) of group(0x2) to scenes table (Endpoint4)
Scene 3:
ESP_ZIGBEE_CORE: Store new scene(0x3) of group(0x3) to scenes table (Endpoint1)
ESP_ZIGBEE_CORE: Store new scene(0x3) of group(0x3) to scenes table (Endpoint2)
ESP_ZIGBEE_CORE: Store new scene(0x3) of group(0x3) to scenes table (Endpoint3)
ESP_ZIGBEE_CORE: Store new scene(0x3) of group(0x3) to scenes table (Endpoint4)
Scene 4:
ESP_ZIGBEE_CORE: Store new scene(0x4) of group(0x4) to scenes table (Endpoint1)
ESP_ZIGBEE_CORE: Store new scene(0x4) of group(0x4) to scenes table (Endpoint2)
ESP_ZIGBEE_CORE: Store new scene(0x4) of group(0x4) to scenes table (Endpoint3)
ESP_ZIGBEE_CORE: Store new scene(0x4) of group(0x4) to scenes table (Endpoint4)
Scene 5:
ESP_ZIGBEE_CORE: Insufficient scenes table for scene(0x5), fail to store it._

I am unable to add more than 16 entries in a zigbee 4 gang light switch with four endpoints. 
So how i can use scene's table entries upto 12 scenes with 48 scene table entries in my case.

**Comment by chshu** [comment]
Duplicate issue, will be addressed in https://github.com/espressif/esp-zigbee-sdk/issues/234#issuecomment-1951059211
