### ISSUE TITLE
ESP_ZIGBEE_CORE  Logs (TZ-639)

### ISSUE THREAD

**Issue by mundevx** [espressif/esp-zigbee-sdk#248]
### Question

Hi, 

I got some errors that i have to handle, and displayed on ESP_ZIGBEE_CORE. As i got 'Endpoint(0x2) not found in the group table for group ID(0x13)' and i want to handle this and add group id 0x13 to endpoint 0x2.
How i can have access to ESP_ZIGBEE_CORE logs?

**Comment by xieqinan** [comment]
@mundevx ,

The error log originates from the description in the specification.

![image](https://github.com/espressif/esp-zigbee-sdk/assets/49604229/9081f419-ab94-444c-9040-41a25560386a)


One way to handle the relationship between groups and endpoints is to use the `esp_zb_zcl_groups_add_group_cmd_req()` function.

**Comment by mundevx** [comment]
Ok,
I have four endpoints and i added four groups={1,2,3,4} using "esp_zb_zcl_groups_add_group_cmd_req()".
Now from gateway, when i add scene, then gateway send response on my device with group=10, scene=10.
Then i got same error "'Endpoint(0x1) not found in the group table for group ID(0x0A)".

I dont know what group id will be generated by gateway, so i cant pre add the unknown groups.

**Comment by xieqinan** [comment]
Hello @mundevx ,

> Now from gateway, when i add scene, then gateway send response on my device with group=10, scene=10.
Then i got same error "'Endpoint(0x1) not found in the group table for group ID(0x0A)".

This behavior is strange; the gateway should respond with the related group ID and scene ID you've set. Could you please provide the usage of `esp_zb_zcl_groups_add_group_cmd_req()` and include the response log?
