### ISSUE TITLE
Example project esp_zigbee_ota is not working (TZ-641)

### ISSUE THREAD

**Issue by makkssim** [espressif/esp-zigbee-sdk#249]
### Answers checklist.

- [X] I have read the documentation [ESP Zigbee SDK Programming Guide](https://docs.espressif.com/projects/esp-zigbee-sdk) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) and ESP Zigbee libs ([esp-zboss-lib](https://components.espressif.com/components/espressif/esp-zboss-lib) and [esp-zigbee-lib](https://components.espressif.com/components/espressif/esp-zigbee-lib)) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.2

### esp-zigbee-lib version.

1.1.1

### esp-zboss-lib version.

1.1.1

### Espressif SoC revision.

ESP32-c6

### What is the expected behavior?

I expected to run the example project and get a result similar to that described in the attached readme file. In particular, that between two devices firmware as client and server, a connection will be established and a file will be transferred.

### What is the actual behavior?

The connection is not established, the file is not transferred.
Screenshot of the client log:
![image](https://github.com/espressif/esp-zigbee-sdk/assets/70913058/fb8401b6-2a92-4732-a9e6-2c0af310fb98)
Screenshot of the server log:
![image](https://github.com/espressif/esp-zigbee-sdk/assets/70913058/5cbc7128-ceea-4f36-a094-d25f09fc356e)
Other projects using zigbee such as esp_zigbee_HA_sample and esp_zigbee_customized_devices work fine on these devices.

### Steps to reproduce.

1. Git clone (https://github.com/espressif/esp-zigbee-sdk) repository
2. Open folder as a project
3. Run

**Comment by kelin6** [comment]
@makkssim 
Based on the server log you provided, it indicates that the server device has not been factory reset. This is likely because the device may have run other Zigbee examples, causing other network parameters to exist. 

Therefore, please erase both the server and client devices. You can use the following commands to erase the devices before downloading the code:
```
idf.py -p <port>  erase-flash flash monitor
```
 For more details, you can refer to [ota_server/README]( https://github.com/espressif/esp-zigbee-sdk/blob/main/examples/esp_zigbee_ota/ota_server/README.md#erase-the-nvram)

**Comment by makkssim** [comment]
Did as you said. Nothing has changed. I am attaching a screenshot from cmd.
![image](https://github.com/espressif/esp-zigbee-sdk/assets/70913058/12fa2135-1e3a-48ff-b6e3-e998cbdc69f9)

**Comment by djorr5** [comment]
You forgot the "flash" and "monitor" after erase-flash

**Comment by makkssim** [comment]
![image](https://github.com/espressif/esp-zigbee-sdk/assets/70913058/105cc572-64a5-4991-a863-b97b17bf196f)
Nothing has changed, the log was just output to cmd instead of vs code in the terminal

**Comment by makkssim** [comment]
thanks for the help
