### ISSUE TITLE
Application Support Sub Layer API: meaning of tx_time field in esp_zb_apsde_data_confirm_s struct (esp_zigbee_aps.h) (TZ-656)

### ISSUE THREAD

**Issue by jackDonati** [espressif/esp-zigbee-sdk#259]
### Question

Can anyone please explain the functionality of the [tx_time ](https://github.com/espressif/esp-zigbee-sdk/blob/main/components/esp-zigbee-lib/include/aps/esp_zigbee_aps.h#L58) field in esp_zb_apsde_data_confirm_s struct form esp_zigbee_aps.h ? 

The documentation only specify that it is a reserved field, but it's not clear if such timestamp refers to the transmission time of the acknowledgement, expressed in the clock domain of the destination node addressed by the data request which has been confirmed by the ack, or otherwise it refers to the actual TX time of the data request whose data confirm has been received and handled by the data confirm callback, expressed in the local clock.

I need to understand this aspect since I'm trying to implement a clock synchronization protocol for wireless nodes based on MAC timestamping. It seems that the RX time of a data indication is currently available in the indication handler callback, but it is not clear if the TX timestamp of a data request can be retrived in some way.

Thank you in advance.

**Comment by xieqinan** [comment]
Hello @jackDonati,

The detailed description of the TxTime of APSDE-confirm is introduced in section 2.2.4.1.2 of the Zigbee spec:

![image](https://github.com/espressif/esp-zigbee-sdk/assets/49604229/fd0c61e5-4b56-49a7-a2c0-128f635bab50)

From the Zigbee stack, it is reserved and always zero. If it is necessary for you, we can provide a fix for the TxTime.

**Comment by jackDonati** [comment]
> Hello @jackDonati,
> 
> The detailed description of the TxTime of APSDE-confirm is introduced in section 2.2.4.1.2 of the Zigbee spec:
> 
> ![image](https://private-user-images.githubusercontent.com/49604229/308466690-fd0c61e5-4b56-49a7-a2c0-128f635bab50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMjY4OTMsIm5iZiI6MTcwOTEyNjU5MywicGF0aCI6Ii80OTYwNDIyOS8zMDg0NjY2OTAtZmQwYzYxZTUtNGI1Ni00OWE3LWEyYzAtMTI4ZjYzNWJhYjUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDEzMjMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyODdmNmQ5NWVlNmQzODNkY2Q1N2FiZjRjMWNmZDYyZTRkNDA3NzM2MGY4MjQzYTViY2UyYjJhYzI2YWU0MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KagW0vyAEaX5-Q7auvUGe_UWJA2tXlaAnaAyKl9lO2k)
> 
> From the Zigbee stack, it is reserved and always zero. If it is necessary for you, we can provide a fix for the TxTime.

Hi @xieqinan. It would be very usefull for users like me who are trying to implement custom high-precision clock synchronization protocols to have read-access to the TxTime value of a APSDE-request in the subsequent APSDE-confirm callback.
I still don't understand if the [RxTime](https://github.com/espressif/esp-zigbee-sdk/blob/main/components/esp-zigbee-lib/include/aps/esp_zigbee_aps.h#L81) value of APSDE-indication (section 2.2.4.1.3 of the Zigbee spec) is already read-accessible from the user code in the destination device, or instead is always zero like the TxTime in APSDE-confirm (but eventually I can check by myself).

It would be great if you can provide this fix for the TxTime (and for the RxTime too if not already implemented, as already mentioned).
Let me know if it is necessary for me to report all this considerations in a new feature request.

Thank you very much for your support!

**Comment by xieqinan** [comment]
@jackDonati ,

No problem, we will provide the new feature support ASAP. Thanks for your patience.

**Comment by jackDonati** [comment]
> @jackDonati ,
> 
> No problem, we will provide the new feature support ASAP. Thanks for your patience.

Ok @xieqinan , thank you so much!
