### ISSUE TITLE
Zigbee Move to level (TZ-658)

### ISSUE THREAD

**Issue by HesselJilderts** [espressif/esp-zigbee-sdk#261]
### Question

I want to configure my ESP32-C6 to move my window blinds but i never get the 'move to level' data on my ESP32-C6. When i read the Zigbee Cluster Library i see that the data is being send as a command, How do i receive this?

**Comment by xieqinan** [comment]
Hello @HesselJilderts ,

The ESP-Zigbee-SDK provides the "moving to level" function with `esp_zb_zcl_level_move_to_level_cmd_req()` of the level control cluster. You can refer to the dimmable_switch example for its usage.
