### ISSUE TITLE
Can't send uint64 with attribute reporting (TZ-690)

### ISSUE THREAD

**Issue by makkssim** [espressif/esp-zigbee-sdk#280]
I'm making my own project based on HA_on_off_light/switch, which will send a uint64 number in addition to the on/off command. To do this, I added an additional cluster with the corresponding attribute to the endpoint.
![image](https://github.com/espressif/esp-zigbee-sdk/assets/70913058/e9b956e8-ae59-4b8b-9566-47e3abcf70b1)
After that I created a function to update the value and report of the attribute. The general appearance of the function was borrowed from another project on Github, where it performed similar functions, except that the attribute type was uint16.
![image](https://github.com/espressif/esp-zigbee-sdk/assets/70913058/dd625c2c-03ec-45e7-8406-31ac8996c4eb)
When the function is called, the following output appears.
![image](https://github.com/espressif/esp-zigbee-sdk/assets/70913058/787edf3f-8854-4816-8f9e-3c9c27416242)
Please tell me what I'm doing wrong

**Comment by xieqinan** [comment]
Hello,

The esp-zigbee-sdk now includes an example demonstrating the usage of ZCL reporting, which is helpful to address this issue. You can refer to the [temperature and thermostat example](https://github.com/espressif/esp-zigbee-sdk/tree/main/examples/esp_zigbee_HA_sample/HA_temperature_sensor).

**Comment by makkssim** [comment]
Thanks, this example helped
