### ISSUE TITLE
Document: maybe typo? (TZ-732)

### ISSUE THREAD

**Issue by acha666** [espressif/esp-zigbee-sdk#305]
https://github.com/espressif/esp-zigbee-sdk/blob/c86f305efc693cef958705ad55b2092bcdde16d5/examples/esp_zigbee_sleep/light_sleep/README.md?plain=1#L103

The markdown file is located in `light_sleep` example but the text is `deep sleep`

**Comment by xieqinan** [comment]
@acha666 ,

Thank you for the reminder; we will rectify it in the next release.
