### ISSUE TITLE
Possible to get date & time from router/hub? (TZ-733)

### ISSUE THREAD

**Issue by darianbjohnson** [espressif/esp-zigbee-sdk#306]
### Question

Is is possible for an end device to obtain/request the current data and time from the zigbee router?

**Comment by xieqinan** [comment]
@darianbjohnson ,

The Zigbee cluster provides the timer cluster for managing time, and Zigbee devices attach a timestamp when sending frames. Which way better suits your requirements?

**Comment by darianbjohnson** [comment]
I just reviewed the time cluster API Documentation…. This is what I need. Is there an example that shows how to use the time cluster API?

**Comment by xieqinan** [comment]
@darianbjohnson ,

We have not provided an example for the timer cluster temporarily. However, you can implement it based on the ZCL specification and refer to the examples of other clusters, such as the [temperature cluster](https://github.com/espressif/esp-zigbee-sdk/tree/main/examples/esp_zigbee_HA_sample/HA_temperature_sensor).

**Comment by chshu** [comment]
@darianbjohnson please reopen if you have any further questions on this topic.
