### ISSUE TITLE
[Feature Request] DOTA (Delta Over-The-Air) - Delta OTA update feature for Zigbee firmware delta updates? (TZ-748)

### ISSUE THREAD

**Issue by Hedda** [espressif/esp-zigbee-sdk#311]
### Is your feature request related to a problem?

Would it be possible to implement support for DOTA (Delta Over-The-Air) update feature for Zigbee firmware delta updates?

This is a feature request though not actually sure if the Zigbee specification supports DOTA (Delta Over-The-Air) updates? That is, I am not sure of a DOTA (Delta Over-The-Air) could currently comply with the Zigbee Standard OTA file format?

This in turn is indirectly related to requests regarding the size of the library and OTA (thus also OTA image size):

* https://github.com/espressif/esp-zigbee-sdk/issues/297
* https://github.com/espressif/esp-zigbee-sdk/issues/201

The point of this feature if the idea is even possible would be to reduce the size of OTA update files for updates via OTAU server.

The general concept of DOTA (Delta Over-The-Air) updates is a variant of FOTA (Firmware-Over-The-Air) that only updates the parts of the firmware that have changed, rather than the entire firmware, thus allowing the firmware image file to be much smaller. 

The reason for this is wanting to keep the firmware image size small, as sometimes a device might otherwise not have enough free space which if it is the case will prevent Zigbee OTA updates via OTAU (Over-the-Air-Upgrade) from working, due to the Zigbee OTA updates needing enough free space on the device to download/cache the new Zigbee OTA image file on the device as well as applying the update or failing back if the OTA update fails during the updating process.

Another benefit of the smaller size is that the reduced size of the firmware image improves the speed of the update process. DOTA is commonly useful for devices that have limited memory or limited bandwidth, as it allows for faster and more efficient updates.

Refereces

- https://www.linkedin.com/pulse/what-ota-fota-dota-embedded-systems-iot-pawan-meena/
- https://www.freertos.org/2022/01/delta-over-the-air-updates.html

**Comment by chshu** [comment]
The delta OTA is supported as a extra IDF component: https://github.com/espressif/idf-extra-components/blob/master/esp_delta_ota/README.md, we will come some docs on how to use it in Zigbee OTA flow.
