### ISSUE TITLE
Adding tolerance attribute for pressure measurement cluster (TZ-756)

### ISSUE THREAD

**Issue by acha666** [espressif/esp-zigbee-sdk#315]
![image](https://github.com/espressif/esp-zigbee-sdk/assets/37405625/fa04a6c7-1742-4688-8ec0-c74b8de01ca1)

https://github.com/espressif/esp-zigbee-sdk/blob/3fbf2325b77c8601703def202911566a99dfe098/components/esp-zigbee-lib/include/zcl/esp_zigbee_zcl_pressure_meas.h#L16-L26

The ZCL Spec shows there is an `tolerance` attribute (ID 0x0003) in pressure measurement cluster but it doesn't exist in `esp_zb_zcl_pressure_measurement_attr_t`

**Comment by xieqinan** [comment]
@acha666 ，

No problem, as it is only an enumerated type that will not affect your project.

**Comment by xieqinan** [comment]
@acha666,

The issue has been fixed in the latest esp-zigbee-sdk version, please update the version and test again.
