### ISSUE TITLE
Full compatibility with newly announced ESP32-H4 and ESP32-C5 MCU SoC models? (TZ-775)

### ISSUE THREAD

**Issue by Hedda** [espressif/esp-zigbee-sdk#317]
### Is your feature request related to a problem?

Just to clearify, will you add full compatibility with the announced ESP32-H4 and ESP32-C5 MCU SoC models to ESP-Zigbee-SDK?

* https://www.espressif.com/en/news/ESP32-H4
* https://www.espressif.com/en/news/ESP32-C5

I understand that ESP32-H4 and ESP32-C5 will be supported in ESP-IDF v5.3 which is scheduled for final release in Q3 of 2024:

https://github.com/espressif/esp-idf/tree/release/v5.3

* The existing ESP32-H2 is a single-core CPU model with 802.15.4 radio and no WiFi.
* The new ESP32-H4 is a dual-core CPU model with 802.15.4 radio and no WiFi, plus optional support for PSRAM.
* The new  ESP32-C5 is a single-core CPU model with 802.15.4 radio and WiFi.
* The existing ESP32-C6 is a dual-core CPU model with 802.15.4 radio and WiFi , plus optional support for PSRAM.

![image](https://github.com/espressif/esp-zigbee-sdk/assets/6320001/793befad-d079-4d29-85a8-d1d547574112)

PS: Also announced is new [ESP32-P4](https://www.cnx-software.com/2023/01/06/espressif-esp32-p4-a-400-mhz-general-purpose-dual-core-risc-v-microcontroller/) which a high-performance MCU SoC without any radios at all, so it is designed to act as a general purpose host MCU that in combination with above SoC to make a 2-SoC solution with Ethernet PHY (like for example a Zigbee Gateway).

https://docs.espressif.com/projects/esp-thread-br/en/latest/hardware_platforms.html

**Comment by chshu** [comment]
> Just to clearify, will you add full compatibility with the announced ESP32-H4 and ESP32-C5 MCU SoC models to ESP-Zigbee-SDK?

Sure thing, the ESP Zigbee SDK will support H4, C5 and future new SoCs.
