### ISSUE TITLE
Zigbee Gateway or Zigbee Host? (TZ-791)

### ISSUE THREAD

**Issue by vritzka** [espressif/esp-zigbee-sdk#320]
### Question

Hi, you provide 2 examples:

[Zigbee Gateway](https://github.com/espressif/esp-zigbee-sdk/tree/main/examples/esp_zigbee_gateway) and [Zigbee Host](https://github.com/espressif/esp-zigbee-sdk/tree/main/examples/esp_zigbee_host).

I am trying to understand the differences.

**Gateway example** seems to be better because it allows automatic firmware updates on the ESP32-H2.

But **host example** has the on/off example running which makes it easier to use.

Which different usage scenarios are those 2 example meant for?

Thank you

**Comment by xieqinan** [comment]
Hello @vritzka ,

Both the Gateway + RCP and Host + NCP can implement the complete Zigbee stack. As we know, the Zigbee stack includes the following layers. The Gateway + RCP splits the stack into the MAC + PHY layers, while the Host + NCP splits the stack into the APS + NWK layers. Therefore, users can choose the example based on different scenarios.


![image](https://github.com/espressif/esp-zigbee-sdk/assets/49604229/898e0caf-9bd5-4181-aba7-ac4d2a56578e)


> Gateway example seems to be better because it allows automatic firmware updates on the ESP32-H2.

> But host example has the on/off example running which makes it easier to use.

These differences only exist in the application layer and depend on the user's implementation. In other words, both automatic firmware updates and on/off operations can be implemented in either the Gateway or Host examples.
