### ISSUE TITLE
Implementing Direct String Sending and Receiving via AF Layer on ESP32H2 (TZ-807)

### ISSUE THREAD

**Issue by zhang-zi-ang** [espressif/esp-zigbee-sdk#324]
### Question

I'm attempting to utilize the AF (Application Framework) layer akin to CC2530 for communication, with the goal of directly sending and receiving strings. However, I couldn't find relevant APIs in my ESP32H2 environment.

I'd like to understand if there's a method to accomplish this process, or if there are other sample routines available to support it.

**Comment by xieqinan** [comment]
@zhang-zi-ang ，

Does the AF (Application Framework) you said indicate the APS(application support) layer of Zigbee?

**Comment by zhang-zi-ang** [comment]
I obtained what I wanted from the following link. [https://github.com/espressif/esp-zigbee-sdk/issues/202]
Could you please tell me if there are any updates to this example?

**Comment by xieqinan** [comment]
@zhang-zi-ang ,

We do not currently plan to add an example for this issue, but we are adding more documentation for the APIs of the esp-zigbee-sdk, which will be helpful for you.

**Comment by zhang-zi-ang** [comment]
@xieqinan 

I encountered the message "receive buffer full, drop the current frame" while using this routine. My IDF version is 5.1.3, and the SDK version is 1.3.2.

**Comment by xieqinan** [comment]
@zhang-zi-ang ，

Please provide the detailed steps for reproducing the `buffer full` issue. This issue has been encountered by other customers as well. Please comment out the log in esp-idf and test again. The log is printed in the ISR, which can block other tasks and is not necessary.
