### ISSUE TITLE
user_ctx always 0x0 in esp_zb_zdo_binding_table_callback_t (TZ-808)

### ISSUE THREAD

**Issue by simonborje** [espressif/esp-zigbee-sdk#325]
### Answers checklist.

- [X] I have read the documentation [ESP Zigbee SDK Programming Guide](https://docs.espressif.com/projects/esp-zigbee-sdk) and tried the [debugging tips](https://docs.espressif.com/projects/esp-zigbee-sdk/en/latest/esp32/developing.html#debugging), the issue is not addressed there.
- [X] I have updated ESP Zigbee libs ([esp-zboss-lib](https://components.espressif.com/components/espressif/esp-zboss-lib) and [esp-zigbee-lib](https://components.espressif.com/components/espressif/esp-zigbee-lib)) to the latest version, with corresponding IDF version, and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

ESP-IDF v5.1.3

### esp-zigbee-lib version.

1.2.3

### esp-zboss-lib version.

1.2.3

### Espressif SoC revision.

ESP32-C6

### What is the expected behavior?

The value of the `void *user_ctx` pointer supplied to the `esp_zb_zdo_binding_table_req()` call should be preserved in the `esp_zb_zdo_binding_table_callback_t` function.

### What is the actual behavior?

The `void *user_ctx` value is always 0x0.

### Steps to reproduce.

1. Call `esp_zb_zdo_binding_table_req()` with a non-zero `user_ctx` argument.
2. Check value of `void *user_ctx` in the callback function `esp_zb_zdo_binding_table_callback_t` which is always 0x0.

**Comment by xieqinan** [comment]
@simonborje ，

The `user_ctx` is set to NULL in the stack, it will be fixed in next version.
