### ISSUE TITLE
APS pkt 12 for ep 1 is not recognized - drop         Why? (TZ-812)

### ISSUE THREAD

**Issue by vritzka** [espressif/esp-zigbee-sdk#329]
### Question

Hello,

I am running **esp_zigbee_gateway** on ESP32s3 + **ot_rcp** on ESP32H2.

As soon as I join a device I get this error:

ZBOSS: zdo/af_rx.c:463   APS pkt 18 for ep 1 is not recognized - drop    
ZBOSS: zdo/af_rx.c:463   APS pkt 3 for ep 1 is not recognized - drop   
ZBOSS: zdo/af_rx.c:463   APS pkt 6 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 12 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 15 for ep 1 is not recognized - drop

.... and more lines like this.

I am joining a switch or a temperature sensor .... both cause this error.

Those switch or temp sensor work well when I run esp_zigbee_host + esp_zigbee_rcp

What do those errors mean?

Thanks

### Additional context.

`I (513) spi_flash: flash io: dio
W (517) spi_flash: Detected size(16384k) larger than the size in the binary image header(4096k). Using the size in the binary image header.
I (530) sleep: Configure to isolate all GPIO pins in sleep state
I (537) sleep: Enable automatic switching of GPIO sleep configuration
I (544) main_task: Started on CPU0
I (554) main_task: Calling app_main()
I (574) ESP_RADIO_SPINEL: spinel UART interface initialization completed
I (574) ESP_RADIO_SPINEL: Spinel UART interface has been successfully enabled
I (574) main_task: Returned from app_main()
I(584) OPENTHREAD:[I] P-RadioSpinel-: RCP reset: RESET_POWER_ON
I(594) OPENTHREAD:[I] P-RadioSpinel-: Software reset RCP successfully
ZBOSS: common/zb_init_default.c:183   FFD build
ZBOSS: common/zb_init_default.c:187   sizes: g_zb 7552 sched 224 bpool 16 nwk 1032 aps 3048 addr 284 zdo 840
ZBOSS: common/zb_init_default.c:196   sec 2
ZBOSS: common/zb_init_default.c:198   zcl 600
ZBOSS: common/zb_init_default.c:201   zll 960
ZBOSS: common/zb_init_default.c:207   nvram 140
ZBOSS: common/zb_init_default.c:210   buttons 200
ZBOSS: common/zb_init_default.c:212   err_ind 4
ZBOSS: common/zb_init_default.c:218   scheduler q size 80
ZBOSS: common/zb_init_default.c:221   g_mac 824 g_imac 28
ZBOSS: common/zb_init_default.c:225   Configurable mem build, use ZBOSS lib defaults = 0
ZBOSS: common/zb_init_default.c:231   ZB_IOBUF_POOL_SIZE 80 ZB_NWK_IN_Q_SIZE 40 ZB_MAC_PENDING_QUEUE_SIZE 20 ZB_APS_DST_BINDING_TABLE_SIZE 16 ZB_APS_BIND_TRANS_TABLE_SIZE 20 ZB_N_APS_RETRANS_ENTRIES 27
ZBOSS: common/zb_init_default.c:261   ZB_N_APS_KEY_PAIR_ARR_MAX_SIZE 64 ZB_IEEE_ADDR_TABLE_SIZE 80 ZB_NEIGHBOR_TABLE_SIZE 64 ZB_NWK_ROUTING_TABLE_SIZE 64 ZB_APS_DUPS_TABLE_SIZE 32
I (704) ESP_ZB_GATEWAY: Running RCP Version: openthread-esp32/fcb76f0671-456c44828; esp32h2;  2024-04-22 12:47:02 UTC
ZBOSS: zdo/zdo_app_prod_conf.c:144   no production config block found
ZBOSS: zdo/zdo_app_prod_conf.c:781   no valid production configuration found, signaling to application
I (724) ESP_ZB_GATEWAY: Production configuration is ready
W (734) ESP_ZB_GATEWAY: Production configuration is not present
I (744) example_connect: Start example_connect.
I (744) pp: pp rom version: e7ae62f
I (754) net80211: net80211 rom version: e7ae62f
I (764) wifi:wifi driver task: 3fca7bdc, prio:23, stack:6656, core=0
I (764) wifi:wifi firmware version: a0511a3
I (764) wifi:wifi certification version: v7.0
I (764) wifi:config NVS flash: enabled
I (774) wifi:config nano formating: disabled
I (774) wifi:Init data frame dynamic rx buffer num: 32
I (784) wifi:Init static rx mgmt buffer num: 5
I (784) wifi:Init management short buffer num: 32
I (794) wifi:Init dynamic tx buffer num: 32
I (794) wifi:Init static tx FG buffer num: 2
I (794) wifi:Init static rx buffer size: 1600
I (804) wifi:Init static rx buffer num: 10
I (804) wifi:Init dynamic rx buffer num: 32
I (814) wifi_init: rx ba win: 6
I (814) wifi_init: tcpip mbox: 32
I (814) wifi_init: udp mbox: 6
I (824) wifi_init: tcp mbox: 6
I (824) wifi_init: tcp tx win: 5760
I (824) wifi_init: tcp rx win: 5760
I (834) wifi_init: tcp mss: 1440
I (834) wifi_init: WiFi IRAM OP enabled
I (844) wifi_init: WiFi RX IRAM OP enabled
I (844) phy_init: phy_version 640,cd64a1a,Jan 24 2024,17:28:12
I (894) wifi:mode : sta (f4:12:fa:ce:63:a0)
I (894) wifi:enable tsf
I (894) example_connect: Connecting to iPhone...
I (894) example_connect: Waiting for IP(s)
I (3304) example_connect: Wi-Fi disconnected, trying to reconnect...
I (5714) example_connect: Wi-Fi disconnected, trying to reconnect...
I (8124) wifi:new:<11,0>, old:<1,0>, ap:<255,255>, sta:<11,0>, prof:1
I (8474) wifi:state: init -> auth (b0)
I (8474) wifi:state: auth -> assoc (0)
I (8484) wifi:state: assoc -> run (10)
I (8654) wifi:connected with iPhone, aid = 1, channel 11, BW20, bssid = f2:98:a8:99:c9:e0
I (8664) wifi:security: WPA2-PSK, phy: bgn, rssi: -55
I (8664) wifi:pm start, type: 1

I (8664) wifi:dp: 1, bi: 102400, li: 3, scale listen interval from 307200 us to 307200 us
I (8674) wifi:set rx beacon pti, rx_bcn_pti: 0, bcn_timeout: 25000, mt_pti: 0, mt_time: 10000
I (8684) wifi:AP's beacon interval = 102400 us, DTIM period = 1
I (9184) wifi:<ba-add>idx:0 (ifx:0, f2:98:a8:99:c9:e0), tid:0, ssn:2, winSize:64
I (10184) esp_netif_handlers: example_netif_sta ip: 172.20.10.7, mask: 255.255.255.240, gw: 172.20.10.1
I (10184) example_connect: Got IPv4 event: Interface "example_netif_sta" address: 172.20.10.7
I (10574) example_connect: Got IPv6 event: Interface "example_netif_sta" address: fe80:0000:0000:0000:f612:faff:fece:63a0, type: ESP_IP6_ADDR_IS_LINK_LOCAL
I (10574) example_common: Connected to example_netif_sta
I (10584) example_common: - IPv4 address: 172.20.10.7,
I (10584) example_common: - IPv6 address: fe80:0000:0000:0000:f612:faff:fece:63a0, type: ESP_IP6_ADDR_IS_LINK_LOCAL
I (10594) wifi:Set ps type: 0, coexist: 0

I (10604) ESP_ZB_GATEWAY: Initialize Zigbee stack
ZBOSS: commissioning/bdb/zdo_commissioning_bdb.c:340   dev type 0, joined 0, ext_pan_id 0, authenticated 0
ZBOSS: commissioning/bdb/zdo_commissioning_bdb.c:549   COMMISSIONING_STOP: app signal 5 comm status 0
I (10624) ESP_ZB_GATEWAY: Device started up in  factory-reset mode
I (10634) ESP_ZB_GATEWAY: Start network formation
ZBOSS: commissioning/bdb/zdo_commissioning_bdb.c:340   dev type 0, joined 0, ext_pan_id 0, authenticated 0
ZBOSS: zdo/zdo_formation.c:208   First start, perform network formation
ZBOSS: nwk/nwk_cr_formation.c:725   iface_idx 0, selected_page 0, logical_channel 13, networks_count 1, energy_level 0
ZBOSS: zdo/zdo_formation.c:78   zb_nlme_network_formation_confirm 25 status 0
W (10824) ESP_ZB_GATEWAY: Network(0xc543) closed, devices joining not allowed.
ZBOSS: commissioning/bdb/zdo_commissioning_bdb.c:549   COMMISSIONING_STOP: app signal 11 comm status 0
I (10834) ESP_ZB_GATEWAY: Formed network successfully (Extended PAN ID: 48:31:b7:ff:fe:c0:3a:a0, PAN ID: 0xc543, Channel:13, Short Address: 0x0000)
I (11464) ESP_ZB_GATEWAY: Network(0xc543) is open for 180 seconds
ZBOSS: commissioning/bdb/zdo_commissioning_bdb.c:549   COMMISSIONING_STOP: app signal 10 comm status 0
I (11474) ESP_ZB_GATEWAY: Network steering started
I (71024) ESP_ZB_GATEWAY: ZDO signal: NWK Device Associated (0x12), status: ESP_OK
ZBOSS: nwk/nwk_cr_join.c:1269   association: status 0, address 0x7d6f, device a4:c1:38:1d:43:c7:bf:ce, mac_iface_idx 0
ZBOSS: secur/bdb_secur.c:397   ACHTUNG: schedule bdb_link_key_refresh_alarm, ref 31
I (71254) ESP_ZB_GATEWAY: ZDO signal: ZDO Device Update (0x30), status: ESP_OK
I (71784) ESP_ZB_GATEWAY: New device commissioned or rejoined (short: 0x7d6f)
ZBOSS: nwk/zb_nwk_ed_aging.c:612   request_timeout=8
I (73234) ESP_ZB_GATEWAY: ZDO signal: ZDO Device Authorized (0x2f), status: ESP_OK
I (73294) ESP_ZB_GATEWAY: Network(0xc543) is open for 180 seconds
ZBOSS: zdo/af_rx.c:463   APS pkt 12 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 15 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 19 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 4 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 11 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 17 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 3 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 8 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 14 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 19 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 21 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 9 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 25 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 18 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 5 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 10 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 14 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 19 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 4 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 9 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 14 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 18 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 3 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 6 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 12 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 15 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 20 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 4 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 9 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 14 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 18 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 3 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 6 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 12 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 15 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 20 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 4 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 9 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 13 for ep 1 is not recognized - drop
ZBOSS: zdo/af_rx.c:463   APS pkt 16 for ep 1 is not recognized - drop
W (255794) ESP_ZB_GATEWAY: Network(0xc543) closed, devices joining not allowed.
I (1084244) example_connect: Wi-Fi disconnected, trying to reconnect...
I (1086654) example_connect: Wi-Fi disconnected, trying to reconnect...
I (1089064) example_connect: Wi-Fi disconnected, trying to reconnect...
I (1091474) example_connect: Wi-Fi disconnected, trying to reconnect...
`

**Comment by xieqinan** [comment]
@vritzka ，

If you haven't modified the original gateway example, it doesn't create any endpoints. Consequently, commands sent from the temperature sensor to the gateway will be dropped.

If you add an endpoint to the gateway, you should double-check the command sent by the temperature sensor. If the command isn't directed to the existing endpoints of the gateway, it will also be dropped.

**Comment by chshu** [comment]
@vritzka please reopen if any follow up questions.
