### ISSUE TITLE
Recommended partition`s size (TZ-813)

### ISSUE THREAD

**Issue by grebenyuk51** [espressif/esp-zigbee-sdk#330]
### Question

In every zigbee sdk`s example there are custom partition table. In those tables always zb_storage partition with length of 16k
Is this general recommendation and 16k is more then enough? Or is it make sense increase partition if I plan to connect 100+ devices to my router? Same question about zb_fct
Thanks!

```
# Name,   Type, SubType, Offset,  Size, Flags
# Note: if you have increased the bootloader size, make sure to update the offsets to avoid overlap
nvs,        data, nvs,      0x9000,  0x6000,
phy_init,   data, phy,      0xf000,  0x1000,
factory,    app,  factory,  0x10000, 900K,
zb_storage, data, fat,      0xf1000, 16K,
zb_fct,     data, fat,      0xf5000, 1K,
```

**Comment by xieqinan** [comment]
@grebenyuk51 ,

Based on the statistics, the coordinator needs to allocate approximately 496 bytes for a new device. You can optimize this based on your project's requirements.

As for the zc_fct partition, it is reserved for manufacturer configuration. You can find more information in the [mfg_tool](https://github.com/espressif/esp-zigbee-sdk/blob/main/tools/mfg_tool/README.md) documentation.

**Comment by grebenyuk51** [comment]
thanks
