### ISSUE TITLE
Is this SDK benefit from a 32.768kHz crystal ?  (TZ-928)

### ISSUE THREAD

**Issue by X-Ryl669** [espressif/esp-zigbee-sdk#364]
### Question

In the BLE case, mounting an 32.768kHz crystal on the 2 specific crystal pin allows the system to go from few mA to tens of µA because the BLE communication can enter light sleep instead of modem sleep between advertisements. 

Shall we expect the same benefit here for Zigbee when mounting a crystal on the PCB? 

I've seen the deep sleep and light sleep example, so I guess it's possible to actually (light or deep) sleep in the (long) poll interval. But in the short time the device is awake, will it go to modem sleep or to light sleep when the radio is silent?

**Comment by xieqinan** [comment]
@X-Ryl669 ，

> Shall we expect the same benefit here for Zigbee when mounting a crystal on the PCB?

The 32.768kHz crystal does not benefit the Zigbee SDK in general cases.

> will it go to modem sleep or to light sleep when the radio is silent?

I believe that it will enter modem sleep mode when the radio is slilent.
