### ISSUE TITLE
Unbind do not stop communication  (TZ-999)

### ISSUE THREAD

**Issue by kgkask** [espressif/esp-zigbee-sdk#383]
### Question

How to stop communication between two devices (coordinator and end device) ?

### Additional context.

I am using a modified version of this code implementation in #202, once the end device join the network it can communicate before even binding process. what I am trying to achieve is reading a certain attribute from end device if it meets the requirements it will be kept in the network, otherwise it will be unbinded. 

some issue I refered to as well #318 and 

to check the issue :
1- I stopped the binding -> still communicate.
2- I implement unbind after binding -> still communicate. 

I want to make sure if there is an easier way to implement this, or what I am doing wrong so the communication still on gaining. 

**_coordinator_**
![image](https://github.com/espressif/esp-zigbee-sdk/assets/169449109/32921435-09e7-44f7-8056-ad268d4ade8c)

**_end device_**
![image](https://github.com/espressif/esp-zigbee-sdk/assets/169449109/f3fc2e9a-86f0-4a29-a6a3-acd8c8aae80e)

send message implementation on **_coordinator_** 
'static void esp_zb_buttons_handler(switch_func_pair_t *button_func_pair) {

  if (button_func_pair->func == SWITCH_ONOFF_TOGGLE_CONTROL) {

    esp_zb_zcl_custom_cluster_cmd_req_t custom_req;

    char *msg= "This message has a length of 230:FFGFI";
    char *value;
    value = (char*)malloc(sizeof(uint8_t)*(strlen(msg) +  1));
    memset(value,0,sizeof(uint8_t)*(strlen(msg)+1));
    ZBM_Set_Zigbee_Attr_String(value,strlen(msg),msg);

    custom_req.zcl_basic_cmd.src_endpoint = HA_ONOFF_SWITCH_ENDPOINT;
    custom_req.zcl_basic_cmd.dst_endpoint =  10;//0xffff; enddevice endpoint ID
    custom_req.zcl_basic_cmd.dst_addr_u.addr_short = 0xffff;
    custom_req.address_mode = ESP_ZB_APS_ADDR_MODE_16_ENDP_PRESENT;
    custom_req.cluster_id = CUSTOM_CLUSTER_ID;
    custom_req.custom_cmd_id = 0x01;
    custom_req.profile_id = ESP_ZB_AF_HA_PROFILE_ID;
    custom_req.direction = ESP_ZB_ZCL_CMD_DIRECTION_TO_SRV;// set to (-->srv) trigger the correct call back function in the ED
    custom_req.data.type = ESP_ZB_ZCL_ATTR_TYPE_CHAR_STRING;
    custom_req.data.value = value;
    
    esp_zb_lock_acquire(portMAX_DELAY);
    esp_zb_zcl_custom_cluster_cmd_req(&custom_req);
    esp_zb_lock_release();

    log_i("Send 'specified custom number' command");
  }
}'

send message implementation on **_end device_** 

'// done converting to Arduino code
static void esp_zb_buttons_handler(switch_func_pair_t *button_func_pair, char *input_msg) {

  if (button_func_pair->func == SWITCH_ONOFF_TOGGLE_CONTROL) {
    
    // direct msg to coordnator
    esp_zb_zcl_custom_cluster_cmd_req_t custom_req;
 
    // Use the received input message
    char *value;
    value = (char*)malloc(sizeof(uint8_t)*(strlen(input_msg) +  1));
    memset(value,0,sizeof(uint8_t)*(strlen(input_msg)+1));
    ZBM_Set_Zigbee_Attr_String(value,strlen(input_msg),input_msg);
    //                              ID  
    esp_zb_zcl_attribute_t attrs = {2, {ESP_ZB_ZCL_ATTR_TYPE_CHAR_STRING, sizeof(value), value}};  

    // 0xffff -> broadcast   0x0000 -> coordinator
    custom_req.zcl_basic_cmd.src_endpoint = HA_ESP_LIGHT_ENDPOINT;
    custom_req.zcl_basic_cmd.dst_endpoint = 1;//0xffff;// broadcast to client endpoint ID
    custom_req.zcl_basic_cmd.dst_addr_u.addr_short = 0xffff; // broadcast address
    custom_req.address_mode = ESP_ZB_APS_ADDR_MODE_16_ENDP_PRESENT;
    custom_req.cluster_id = CUSTOM_CLUSTER_ID;//
    custom_req.custom_cmd_id = 0x02;// sent message custom cmd ID 
    custom_req.profile_id = ESP_ZB_AF_HA_PROFILE_ID;
    custom_req.direction = ESP_ZB_ZCL_CMD_DIRECTION_TO_CLI;//ESP_ZB_ZCL_CMD_DIRECTION_TO_SRV;
    custom_req.data.type = ESP_ZB_ZCL_ATTR_TYPE_CHAR_STRING;//ESP_ZB_ZCL_ATTR_TYPE_32BIT_ARRAY;
    custom_req.data.value = value;
    
    esp_zb_lock_acquire(portMAX_DELAY);
    esp_zb_zcl_custom_cluster_cmd_req(&custom_req);
    esp_zb_lock_release();

    log_i("Send 'specified custom number' command");
    log_w("%02x",input_msg[0]);
  }
}'

**Comment by lpy4105** [comment]
You are sending commands using a network broadcast address, which is irrelevant to bindings.

Binding enables the source device to send APS data without DstAddress and DstEndpoint (i.g. `ESP_ZB_APS_ADDR_MODE_DST_ADDR_ENDP_NOT_PRESENT` mode). In such mode, the DstAddress and DstEndpoint will be determined by search the binding table on the device.

**Comment by kgkask** [comment]
thanks for quick reply @lpy4105 , 

I found that the by printing the binding table and find that the entries were removed after calling `esp_zb_zdo_device_unbind_req()`, however I am facing now the issue of sending the string data thro APS I tried different modes and still it is not received by both coordinator and end device.  I am using code in #202.

**Comment by lpy4105** [comment]
> however I am facing now the issue of sending the string data thro APS

I guess you want to read "long" string attribute by `read attribute command`. Please update to the latest SDK and have a try. We had some fixes on such issue.

**Comment by kgkask** [comment]
I am using Arduino IDE not sure if the SDK got updated there. but I will check it. 


one more thing I need a report command not read only. I will implement and check if it worked. 

one question: does this mean `custom_cmds `are only used for network not application layer?

**Comment by lpy4105** [comment]
> one more thing I need a report command not read only. I will implement and check if it worked. 

Report should also work in the latest SDK.

> one question: does this mean `custom_cmds `are only used for network not application-sublayer? 

"custom_cmds" you are using is a concept in ZCL over the AF and APS layer. The command is sent via APS data service which supports 4 kind of DstAddrMode. Using the network address is just one of them.

**Comment by kgkask** [comment]
@lpy4105  I tried the write command from the coordinator to end device and it works just fine, however it does not go in the other direction ( from End device to Coordinator) not sure why?! 

I tried the report from the end point as well and it is not recognized be the coordinator at all not sure why?!


@lpy4105  could you please give example of how to use `custom_command's ` as APS command so that I can stop them when end device is unbind from the coordinator. 

Much thanks @lpy4105  <3

**Comment by lpy4105** [comment]
>I tried the write command from the coordinator to end device and it works just fine, however it does not go in the other direction ( from End device to Coordinator) not sure why?!

Conceptually, the ZCL communications are using server/client model, and don't care about the "device role" (i.e. ZC/ZR/ZED).
Back to your case, I assume you have a "custom cluster client" on the zigbee coordinator (ZC) and the same "custom cluster server" on the zigbee end device (ZED). If you want to "write attribute" to the "custom cluster client" on ZC, there must be an attribute in the "custom cluster client".

>could you please give example of how to use custom_command's  as APS command so that I can stop them when end device is unbind from the coordinator.

You can refer to the [HA_thermostat](https://github.com/espressif/esp-zigbee-sdk/tree/main/examples/esp_zigbee_HA_sample/HA_thermostat) and [HA_temperature_sensor](https://github.com/espressif/esp-zigbee-sdk/tree/main/examples/esp_zigbee_HA_sample/HA_temperature_sensor) examples.

Here is the code that send command via Bindings:
https://github.com/espressif/esp-zigbee-sdk/blob/81ade242bb701c8aa74d175bdcdbf8610737f3c5/examples/esp_zigbee_HA_sample/HA_thermostat/main/esp_zb_thermostat.c#L60-L64

**Comment by kgkask** [comment]
So you mean I have to declare a 2 cluster in each side (client and server) so It will be as follows:
ZC                                             ZED
Server ---------WRT-----------> client

client <-----------WRT--------- Server 

Much thanks for your responses.

**Comment by lpy4105** [comment]
> So you mean I have to declare a 2 cluster in each side

Generally speaking, YES. 
However it really depends on how you defines your custom cluster. It is possible to have attribute on both Server and Client side with the same attribute id.

> So is there a way to just remove the device from the network

I think you could try `esp_zb_zdo_device_leave_req`.

**Comment by kgkask** [comment]
I implement it and it works however it seems that it remove the coordinator itself from the network, since when I initiated from the coordinator side while 2 end devices connected none of the devices could communicate. 
 
 anyhow I found way to implemented, however I am wondering if there is way to send backpack info with the response to any command. for example for write_cmd() the response I receive is 1082262485. which is obtained from `    log_e( "Received message: data (%d)", message->variables);`  so if there is it would be extremely helpful 
 
![image](https://github.com/espressif/esp-zigbee-sdk/assets/169449109/83f579dd-1f9e-406b-a975-ff90cddab168)


last point, for the documentation I could not find something which is very detailed currently I am using : https://zigbeealliance.org/wp-content/uploads/2019/11/docs-05-3474-21-0csg-zigbee-specification.pdf
![image](https://github.com/espressif/esp-zigbee-sdk/assets/169449109/afb93033-0139-47ba-a2d7-2cb384085694)

**Comment by lpy4105** [comment]
`write attributes command` and `write attributes response command` are defined in the ZCL (zigbee cluster library) spec. You can also find the defination of the structures in our headers:
https://github.com/espressif/esp-zigbee-sdk/blob/81ade242bb701c8aa74d175bdcdbf8610737f3c5/components/esp-zigbee-lib/include/zcl/esp_zigbee_zcl_command.h#L2016-L2029
Or online API reference:
https://docs.espressif.com/projects/esp-zigbee-sdk/en/latest/esp32h2/api-reference/zcl/esp_zigbee_zcl_command.html#_CPPv437esp_zb_zcl_write_attr_resp_variable_s

**Comment by kgkask** [comment]
I am aware about them, but I am not sure how to initiate the response. Shall it go inside the handler for the write response? 

```
write_attr_handler(){


esp_zb_zcl_write_attr_cmd_resp();
}
```

my issue I could not find the command, and will it override the automated one. 


and much thanks for your patience and responses.

**Comment by kgkask** [comment]
Okay, 

That make sense and meet my understanding, so much thanks, and I will look for work around to implement my application.
