### ISSUE TITLE
Does ESP32-H2 or ESP32-C6 support Zigbee Sleepy End Device? (TZ-154)

### ISSUE THREAD

**Issue by jayavanth** [espressif/esp-zigbee-sdk#39]
I can't seem to keep connection alive to Zigbee coordinator on ESP32-C6 when it's in light sleep or deep sleep. Is it possible to keep zigbee alive when the device is in those sleep modes?

**Comment by kelin6** [comment]
@jayavanth The ESP32-C6 supports light sleep mode in the esp-idf, but the current version of the esp-zigbee-sdk does not support Zigbee Sleepy End Devices. However, support for Zigbee Sleepy End Devices will be added in the next version of the esp-zigbee-sdk.

On the other hand, the ESP32-H2 does not currently support light sleep mode in the esp-idf. Therefore, we plan to add support for light sleep mode in the next version of the esp-idf.

**Comment by jayavanth** [comment]
Thank you!
