### ISSUE TITLE
zigbee raw_command_handler (TZ-1027)

### ISSUE THREAD

**Issue by mbarga82** [espressif/esp-zigbee-sdk#391]
### Question

how to use the esp_zb_raw_command_handler_register to handle the zigbee raw data buffer . I mean how to use the uint8_t bufid returned by the callback to get access to the buffer raw data

**Comment by Alfff** [comment]
@mbarga82 see this [comment](https://github.com/espressif/esp-zigbee-sdk/issues/94#issuecomment-1706103321)

**Comment by chshu** [comment]
@mbarga82 Could you let us know your requirement to handle the raw data buffer? As it's not a recommended way, and we suggest to use the common data model APIs instead.
