### ISSUE TITLE
How to update OTA firmware with Home Assistant (zigbee) (TZ-1037)

### ISSUE THREAD

**Issue by mundevx** [espressif/esp-zigbee-sdk#399]
### Question

Hi,
I need some help in OTA update of zigbee devices through Home Assistant. How i can do this? I read many documents, i tried and but failed to execute OTA update from Home Assistant. May be there is some .json file from manufacturer(espressif) is required in home assistant.

**Comment by xieqinan** [comment]
@mundevx ,

This issue is a duplicate of this one: https://github.com/espressif/esp-zigbee-sdk/issues/393. Please close it.
