### ISSUE TITLE
Multiple Endpoints (TZ-1070)

### ISSUE THREAD

**Issue by Gazelle84** [espressif/esp-zigbee-sdk#407]
### Question

Hi, I’m trying to create multiple endpoints for an esp32-h2 and just cannot get more than one to register in zigbee2mqqt. I’m using the zigbee HA light example which works fine with the provided code. I have used the same code and some snippets to try and add a switch, which compiles but doesn’t register the switch. 

if I comment out the light code, it builds and registers the switch, but with both there it only registers the light. 

Do I need to create a list of endpoints and register the list? Or do I register them individually? I have tried numbering them from 1 and it behaves the same.

I want to connect around 5 devices to the gpio pins and control them individually. They will be a simple on/off switch. I can’t find any example where multiple endpoints are registered.

**Comment by xieqinan** [comment]
@Gazelle84 ,

The code below registers five endpoints to the device. You can use it as a reference for your project.
```
    esp_zb_on_off_switch_cfg_t switch_cfg = ESP_ZB_DEFAULT_ON_OFF_SWITCH_CONFIG();
    esp_zb_ep_list_t *ep_list = esp_zb_ep_list_create();
    for (int i = 0; i < 5; i++) {
        esp_zb_endpoint_config_t endpoint_config = {
            .endpoint = HA_ONOFF_SWITCH_ENDPOINT + i,
            .app_profile_id = ESP_ZB_AF_HA_PROFILE_ID,
            .app_device_id = ESP_ZB_HA_ON_OFF_SWITCH_DEVICE_ID,
            .app_device_version = 0,
        };
        zcl_basic_manufacturer_info_t info = {
            .manufacturer_name = ESP_MANUFACTURER_NAME,
            .model_identifier = ESP_MODEL_IDENTIFIER,
        };
        esp_zb_ep_list_add_ep(ep_list, esp_zb_on_off_switch_clusters_create(&switch_cfg), endpoint_config);
        esp_zcl_utility_add_ep_basic_manufacturer_info(ep_list, HA_ONOFF_SWITCH_ENDPOINT + i, &info);
    }
    esp_zb_device_register(ep_list);
```

**Comment by Gazelle84** [comment]
Superb, thanks, i will give it a try and report back.

**Comment by xGreenPandax** [comment]
Doesnt work for me. I only see the first endpoint in coordinator app

**Comment by chshu** [comment]
@Gazelle84 @xGreenPandax Any update on this issue?

**Comment by xGreenPandax** [comment]
@chshu nothing. Is it possible to provide complete example with multiple different endpoints?

**Comment by Daniel-Craciun** [comment]
Hello everyone, I've managed to get multiple endpoints working with my home made coordinator. What solved the issue for me, was that In my end device I removed the code which updates the attribute reporting info ie. I removed this line from my end device `ESP_ERROR_CHECK(esp_zb_zcl_update_reporting_info(&reporting_info));` and everything started working like a charm. Hope this can help anyone :)

**Comment by Gazelle84** [comment]
This is the code i ended up with:

file = esp_zb_light.c

/*
 * SPDX-FileCopyrightText: 2021-2022 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: CC0-1.0
 *
 * Zigbee HA_on_off_light Example
 *
 * This example code is in the Public Domain (or CC0 licensed, at your option.)
 *
 * Unless required by applicable law or agreed to in writing, this
 * software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, either express or implied.
 */

// Include necessary headers that provide access to various libraries and functions
#include "esp_zb_light.h" // Zigbee light-related functions
#include "esp_check.h" // Error-checking macros
#include "esp_log.h" // Logging functions for debugging
#include "nvs_flash.h" // Flash memory functions (non-volatile storage)
#include "freertos/FreeRTOS.h" // Real-time operating system for task management
#include "freertos/task.h" // FreeRTOS task handling
#include "ha/esp_zigbee_ha_standard.h" // Zigbee Home Automation standard functions
#include "esp_err.h"
#include "string.h"
#include "driver/gpio.h"


// Check if the Zigbee End Device role is defined. If not, throw an error.
#if !defined ZB_ED_ROLE
#error Define ZB_ED_ROLE in idf.py menuconfig to compile light (End Device) source code.
#endif

// Define a constant string to be used as a tag for logging messages
static const char *TAG = "ESP_ZB_ON_OFF_LIGHT";

/********************* Define functions **************************/

//function to initialize the GPIO pins as outputs
static void init_gpio_pins(void) {
    gpio_config_t io_conf = {};
    io_conf.intr_type = GPIO_INTR_DISABLE;
    io_conf.mode = GPIO_MODE_OUTPUT;
    io_conf.pin_bit_mask = (1ULL << SOLENOID_1_GPIO) | (1ULL << SOLENOID_2_GPIO) | (1ULL << SOLENOID_3_GPIO) | (1ULL << SOLENOID_4_GPIO);
    io_conf.pull_down_en = GPIO_PULLDOWN_DISABLE;
    io_conf.pull_up_en = GPIO_PULLUP_DISABLE;
    gpio_config(&io_conf);
}

/**
 * @brief This function initializes the light driver with a default state (off).
 * 
 * @return esp_err_t ESP_OK indicates successful execution.
 */
static esp_err_t deferred_driver_init(void)
{
    light_driver_init(LIGHT_DEFAULT_OFF); // Initialize the light driver with the light off
    return ESP_OK; // Return OK to indicate success
}

/**
 * @brief This function is a callback that starts the top-level commissioning process in Zigbee.
 * 
 * @param mode_mask Specifies the commissioning mode to start.
 */
static void bdb_start_top_level_commissioning_cb(uint8_t mode_mask)
{
    // Start commissioning and check if it succeeds. If not, log an error message.
    ESP_RETURN_ON_FALSE(esp_zb_bdb_start_top_level_commissioning(mode_mask) == ESP_OK, , TAG, "Failed to start Zigbee commissioning");
}

/**
 * @brief This function handles various Zigbee signals, determining what action to take based on the signal type.
 * 
 * @param signal_struct Pointer to a structure containing the signal and associated status.
 */
void esp_zb_app_signal_handler(esp_zb_app_signal_t *signal_struct)
{
    // Extract the signal type and error status from the signal structure
    uint32_t *p_sg_p = signal_struct->p_app_signal;
    esp_err_t err_status = signal_struct->esp_err_status;
    esp_zb_app_signal_type_t sig_type = *p_sg_p;

    // Switch statement to handle different signal types
    switch (sig_type) {
    case ESP_ZB_ZDO_SIGNAL_SKIP_STARTUP:
        // If startup is skipped, initialize the Zigbee stack
        ESP_LOGI(TAG, "Initialize Zigbee stack");
        esp_zb_bdb_start_top_level_commissioning(ESP_ZB_BDB_MODE_INITIALIZATION); // Start initialization
        break;

    case ESP_ZB_BDB_SIGNAL_DEVICE_FIRST_START:
    case ESP_ZB_BDB_SIGNAL_DEVICE_REBOOT:
        // Handle device's first start or reboot
        if (err_status == ESP_OK) {
            // If no error, initialize the light driver and log the status
            ESP_LOGI(TAG, "Deferred driver initialization %s", deferred_driver_init() ? "failed" : "successful");
            ESP_LOGI(TAG, "Device started up in %s factory-reset mode", esp_zb_bdb_is_factory_new() ? "" : "non");
            
            // If the device is new (factory reset), start network steering
            if (esp_zb_bdb_is_factory_new()) {
                ESP_LOGI(TAG, "Start network steering");
                esp_zb_bdb_start_top_level_commissioning(ESP_ZB_BDB_MODE_NETWORK_STEERING);
            } else {
                // Otherwise, just log that the device rebooted
                ESP_LOGI(TAG, "Device rebooted");
            }
        } else {
            // If there was an error, log a warning with the error status
            ESP_LOGW(TAG, "Failed to initialize Zigbee stack (status: %s)", esp_err_to_name(err_status));
        }
        break;

    case ESP_ZB_BDB_SIGNAL_STEERING:
        // Handle network steering signal
        if (err_status == ESP_OK) {
            // If successful, log the extended PAN ID, PAN ID, channel, and short address
            esp_zb_ieee_addr_t extended_pan_id;
            esp_zb_get_extended_pan_id(extended_pan_id);
            ESP_LOGI(TAG, "Joined network successfully (Extended PAN ID: %02x:%02x:%02x:%02x:%02x:%02x:%02x:%02x, PAN ID: 0x%04hx, Channel:%d, Short Address: 0x%04hx)",
                     extended_pan_id[7], extended_pan_id[6], extended_pan_id[5], extended_pan_id[4],
                     extended_pan_id[3], extended_pan_id[2], extended_pan_id[1], extended_pan_id[0],
                     esp_zb_get_pan_id(), esp_zb_get_current_channel(), esp_zb_get_short_address());
        } else {
            // If steering was not successful, log an info message and retry commissioning after 1 second
            ESP_LOGI(TAG, "Network steering was not successful (status: %s)", esp_err_to_name(err_status));
            esp_zb_scheduler_alarm((esp_zb_callback_t)bdb_start_top_level_commissioning_cb, ESP_ZB_BDB_MODE_NETWORK_STEERING, 1000);
        }
        break;

    default:
        // Handle any other Zigbee signals by logging the signal type and status
        ESP_LOGI(TAG, "ZDO signal: %s (0x%x), status: %s", esp_zb_zdo_signal_to_string(sig_type), sig_type,
                 esp_err_to_name(err_status));
        break;
    }
}

/**
 * @brief This function handles attribute changes (e.g., turning the light on/off) received over Zigbee.
 * 
 * @param message Pointer to the message containing the attribute change.
 * @return esp_err_t Returns ESP_OK if the message is handled successfully.
 */
static esp_err_t zb_attribute_handler(const esp_zb_zcl_set_attr_value_message_t *message)
{
    esp_err_t ret = ESP_OK;
    bool state = 0;

    ESP_RETURN_ON_FALSE(message, ESP_FAIL, TAG, "Empty message");
    ESP_RETURN_ON_FALSE(message->info.status == ESP_ZB_ZCL_STATUS_SUCCESS, ESP_ERR_INVALID_ARG, TAG, "Received message: error status(%d)",
                        message->info.status);

    ESP_LOGI(TAG, "Received message: endpoint(%d), cluster(0x%x), attribute(0x%x), data size(%d)", message->info.dst_endpoint, message->info.cluster,
             message->attribute.id, message->attribute.data.size);

    if (message->info.cluster == ESP_ZB_ZCL_CLUSTER_ID_ON_OFF) {
        if (message->attribute.id == ESP_ZB_ZCL_ATTR_ON_OFF_ON_OFF_ID && message->attribute.data.type == ESP_ZB_ZCL_ATTR_TYPE_BOOL) {
            state = *(bool *)message->attribute.data.value;

            switch (message->info.dst_endpoint) {
                case HA_ESP_LIGHT_ENDPOINT:
                    ESP_LOGI(TAG, "Light sets to %s", state ? "On" : "Off");
                    light_driver_set_power(state);
                    break;

                case HA_ONOFF_SOLENOID_ENDPOINT_1:
                    ESP_LOGI(TAG, "Solenoid 1 sets to %s", state ? "On" : "Off");
                    gpio_set_level(SOLENOID_1_GPIO, state);
                    break;

                case HA_ONOFF_SOLENOID_ENDPOINT_2:
                    ESP_LOGI(TAG, "Solenoid 2 sets to %s", state ? "On" : "Off");
                    gpio_set_level(SOLENOID_2_GPIO, state);
                    break;
                case HA_ONOFF_SOLENOID_ENDPOINT_3:
                    ESP_LOGI(TAG, "Solenoid 3 sets to %s", state ? "On" : "Off");
                    gpio_set_level(SOLENOID_3_GPIO, state);
                    break;

                case HA_ONOFF_SOLENOID_ENDPOINT_4:
                    ESP_LOGI(TAG, "Solenoid 4 sets to %s", state ? "On" : "Off");
                    gpio_set_level(SOLENOID_4_GPIO, state);
                    break;

                default:
                    ESP_LOGW(TAG, "Unknown endpoint: %d", message->info.dst_endpoint);
                    break;
            }
        }
    }

    return ret;
}

/**
 * @brief This function handles various Zigbee actions and routes them to the appropriate handler.
 * 
 * @param callback_id The ID of the action callback.
 * @param message Pointer to the message associated with the action.
 * @return esp_err_t Returns ESP_OK if the action is handled successfully.
 */
static esp_err_t zb_action_handler(esp_zb_core_action_callback_id_t callback_id, const void *message)
{
    esp_err_t ret = ESP_OK;

    // Handle the action based on the callback ID
    switch (callback_id) {
    case ESP_ZB_CORE_SET_ATTR_VALUE_CB_ID:
        // If the action is to set an attribute value, handle it using the attribute handler
        ret = zb_attribute_handler((esp_zb_zcl_set_attr_value_message_t *)message);
        break;
    default:
        // If the action is unknown, log a warning
        ESP_LOGW(TAG, "Receive Zigbee action(0x%x) callback", callback_id);
        break;
    }
    return ret;
}

/**
 * @brief This is the main Zigbee task that initializes and starts the Zigbee stack.
 * 
 * @param pvParameters Pointer to parameters passed to the task (unused here).
 */
static void esp_zb_task(void *pvParameters)
{
    // Initialize the Zigbee network configuration with default settings
    esp_zb_cfg_t zb_nwk_cfg = ESP_ZB_ZED_CONFIG();
    esp_zb_init(&zb_nwk_cfg);

    // Initialize GPIO pins for solenoids
    init_gpio_pins();

    // Create a list of endpoints. An endpoint represents a logical device on the Zigbee network.
    // This list will store all the endpoints that are being configured in the loop below.
    esp_zb_ep_list_t *ep_list = esp_zb_ep_list_create();

    



    // Configure the on/off light with default settings
    esp_zb_on_off_light_cfg_t light_cfg = ESP_ZB_DEFAULT_ON_OFF_LIGHT_CONFIG();

//****Light 1 Config****//

    // Create a Zigbee endpoint for the light with the specified configuration
    //esp_zb_ep_list_t *esp_zb_on_off_light_ep = esp_zb_on_off_light_ep_create(HA_ESP_LIGHT_ENDPOINT, &light_cfg);

    esp_zb_endpoint_config_t light_endpoint_config = {
        .endpoint = HA_ESP_LIGHT_ENDPOINT, // Assign a unique endpoint number by adding i to the base endpoint.
        .app_profile_id = ESP_ZB_AF_HA_PROFILE_ID, // Use the Home Automation profile ID for Zigbee.
        .app_device_id = ESP_ZB_HA_ON_OFF_LIGHT_DEVICE_ID, // Specify that this endpoint is a light device.
        .app_device_version = 0, // Set the device version to 0 (default version).
    };

    //Add light to endpoint list
    esp_zb_ep_list_add_ep(ep_list, esp_zb_on_off_light_clusters_create(&light_cfg), light_endpoint_config);

    // Set manufacturer-specific information (e.g., name, model) for the light
    zcl_basic_manufacturer_info_t light_1_info = {
        .manufacturer_name = ESP_MANUFACTURER_NAME,
        .model_identifier = ESP_MODEL_IDENTIFIER,
    };
    
    esp_zcl_utility_add_ep_basic_manufacturer_info(ep_list, HA_ESP_LIGHT_ENDPOINT, &light_1_info);

//****End Light 1 Config****//



//****Solenoid 1 Config****//

    // Create a Zigbee endpoint for the light with the specified configuration
    //esp_zb_ep_list_t *esp_zb_on_off_light_ep = esp_zb_on_off_light_ep_create(HA_ESP_LIGHT_ENDPOINT, &light_cfg);

    esp_zb_endpoint_config_t solenoid_endpoint_config_1 = {
        .endpoint = HA_ONOFF_SOLENOID_ENDPOINT_1, // Assign a unique endpoint number by adding i to the base endpoint.
        .app_profile_id = ESP_ZB_AF_HA_PROFILE_ID, // Use the Home Automation profile ID for Zigbee.
        .app_device_id = ESP_ZB_HA_ON_OFF_LIGHT_DEVICE_ID, // Specify that this endpoint is a light device.
        .app_device_version = 0, // Set the device version to 0 (default version).
    };

    //Add light to endpoint list
    esp_zb_ep_list_add_ep(ep_list, esp_zb_on_off_light_clusters_create(&light_cfg), solenoid_endpoint_config_1);

    // Set manufacturer-specific information (e.g., name, model) for the light
    zcl_basic_manufacturer_info_t solenoid_1_info = {
        .manufacturer_name = ESP_MANUFACTURER_NAME,
        .model_identifier = ESP_MODEL_IDENTIFIER,
    };
    
    esp_zcl_utility_add_ep_basic_manufacturer_info(ep_list, HA_ONOFF_SOLENOID_ENDPOINT_1, &solenoid_1_info);

//****End Solenoid 1 Config****//


//****Solenoid 2 Config****//

    // Create a Zigbee endpoint for the light with the specified configuration
    //esp_zb_ep_list_t *esp_zb_on_off_light_ep = esp_zb_on_off_light_ep_create(HA_ESP_LIGHT_ENDPOINT, &light_cfg);

    esp_zb_endpoint_config_t solenoid_endpoint_config_2 = {
        .endpoint = HA_ONOFF_SOLENOID_ENDPOINT_2, // Assign a unique endpoint number by adding i to the base endpoint.
        .app_profile_id = ESP_ZB_AF_HA_PROFILE_ID, // Use the Home Automation profile ID for Zigbee.
        .app_device_id = ESP_ZB_HA_ON_OFF_LIGHT_DEVICE_ID, // Specify that this endpoint is a light device.
        .app_device_version = 0, // Set the device version to 0 (default version).
    };

    //Add light to endpoint list
    esp_zb_ep_list_add_ep(ep_list, esp_zb_on_off_light_clusters_create(&light_cfg), solenoid_endpoint_config_2);

    // Set manufacturer-specific information (e.g., name, model) for the light
    zcl_basic_manufacturer_info_t solenoid_2_info = {
        .manufacturer_name = ESP_MANUFACTURER_NAME,
        .model_identifier = ESP_MODEL_IDENTIFIER,
    };
    
    esp_zcl_utility_add_ep_basic_manufacturer_info(ep_list, HA_ONOFF_SOLENOID_ENDPOINT_2, &solenoid_2_info);

//****End Solenoid 2 Config****//


//****Solenoid 3 Config****//

    // Create a Zigbee endpoint for the light with the specified configuration
    //esp_zb_ep_list_t *esp_zb_on_off_light_ep = esp_zb_on_off_light_ep_create(HA_ESP_LIGHT_ENDPOINT, &light_cfg);

    esp_zb_endpoint_config_t solenoid_endpoint_config_3 = {
        .endpoint = HA_ONOFF_SOLENOID_ENDPOINT_3, // Assign a unique endpoint number by adding i to the base endpoint.
        .app_profile_id = ESP_ZB_AF_HA_PROFILE_ID, // Use the Home Automation profile ID for Zigbee.
        .app_device_id = ESP_ZB_HA_ON_OFF_LIGHT_DEVICE_ID, // Specify that this endpoint is a light device.
        .app_device_version = 0, // Set the device version to 0 (default version).
    };

    //Add light to endpoint list
    esp_zb_ep_list_add_ep(ep_list, esp_zb_on_off_light_clusters_create(&light_cfg), solenoid_endpoint_config_3);

    // Set manufacturer-specific information (e.g., name, model) for the light
    zcl_basic_manufacturer_info_t solenoid_3_info = {
        .manufacturer_name = ESP_MANUFACTURER_NAME,
        .model_identifier = ESP_MODEL_IDENTIFIER,
    };
    
    esp_zcl_utility_add_ep_basic_manufacturer_info(ep_list, HA_ONOFF_SOLENOID_ENDPOINT_3, &solenoid_3_info);

//****End Solenoid 3 Config****//

//****Solenoid 4 Config****//

    // Create a Zigbee endpoint for the light with the specified configuration
    //esp_zb_ep_list_t *esp_zb_on_off_light_ep = esp_zb_on_off_light_ep_create(HA_ESP_LIGHT_ENDPOINT, &light_cfg);

    esp_zb_endpoint_config_t solenoid_endpoint_config_4 = {
        .endpoint = HA_ONOFF_SOLENOID_ENDPOINT_4, // Assign a unique endpoint number by adding i to the base endpoint.
        .app_profile_id = ESP_ZB_AF_HA_PROFILE_ID, // Use the Home Automation profile ID for Zigbee.
        .app_device_id = ESP_ZB_HA_ON_OFF_LIGHT_DEVICE_ID, // Specify that this endpoint is a light device.
        .app_device_version = 0, // Set the device version to 0 (default version).
    };

    //Add light to endpoint list
    esp_zb_ep_list_add_ep(ep_list, esp_zb_on_off_light_clusters_create(&light_cfg), solenoid_endpoint_config_4);

    // Set manufacturer-specific information (e.g., name, model) for the light
    zcl_basic_manufacturer_info_t solenoid_4_info = {
        .manufacturer_name = ESP_MANUFACTURER_NAME,
        .model_identifier = ESP_MODEL_IDENTIFIER,
    };
    
    esp_zcl_utility_add_ep_basic_manufacturer_info(ep_list, HA_ONOFF_SOLENOID_ENDPOINT_4, &solenoid_4_info);

//****End Solenoid 4 Config****//


    // Register the device with the list of configured endpoints on the Zigbee network.
    // This function will finalize the setup and make the device visible and operational on the Zigbee network.
    esp_zb_device_register(ep_list);

    // Register single endpoint device with the Zigbee stack
    //esp_zb_device_register(esp_zb_on_off_light_ep);

    // Register the action handler to manage Zigbee core actions
    esp_zb_core_action_handler_register(zb_action_handler);

    // Set the primary Zigbee network channels to be used
    esp_zb_set_primary_network_channel_set(ESP_ZB_PRIMARY_CHANNEL_MASK);

    // Start the Zigbee stack and check for errors
    ESP_ERROR_CHECK(esp_zb_start(false));

    // Enter the main Zigbee loop to handle events and communication
    esp_zb_main_loop_iteration();
}

/**
 * @brief The main entry point of the application.
 */
void app_main(void)
{
    // Configure the Zigbee platform with default radio and host settings
    esp_zb_platform_config_t config = {
        .radio_config = ESP_ZB_DEFAULT_RADIO_CONFIG(),
        .host_config = ESP_ZB_DEFAULT_HOST_CONFIG(),
    };

    // Initialize non-volatile flash storage (used to store persistent data)
    ESP_ERROR_CHECK(nvs_flash_init());

    // Configure the Zigbee platform with the previously set config
    ESP_ERROR_CHECK(esp_zb_platform_config(&config));

    // Create the main Zigbee task with a stack size of 4096 bytes, a priority of 5, and no parameters
    xTaskCreate(esp_zb_task, "Zigbee_main", 4096, NULL, 5, NULL);
}



file = esp_zb_light.h

/*
 * SPDX-FileCopyrightText: 2021-2022 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: CC0-1.0
 *
 * Zigbee HA_on_off_light Example
 *
 * This example code is in the Public Domain (or CC0 licensed, at your option.)
 *
 * Unless required by applicable law or agreed to in writing, this
 * software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, either express or implied.
 */

/* Include the core Zigbee functionality, light driver, and ZCL utilities */
#include "esp_zigbee_core.h"  // Core Zigbee functionality: networking, roles, stack
#include "light_driver.h"      // Light driver functions: on/off control, brightness
#include "switch_driver.h"
#include "zcl_utility.h"       // Zigbee Cluster Library (ZCL) utilities: standardized commands

/* Zigbee configuration settings specific to this example */

/* 
 * Enable or disable the install code policy for device security.
 * If set to true, the device will use an install code for security.
 * Set to false, so install code policy is disabled.
 */
#define INSTALLCODE_POLICY_ENABLE       false

/*
 * Set the aging timeout for End Devices (ED).
 * This represents the time after which inactive End Devices are aged out.
 * Using a predefined constant that represents a timeout of 64 minutes.
 */
#define ED_AGING_TIMEOUT                ESP_ZB_ED_AGING_TIMEOUT_64MIN

/*
 * Define the keep-alive interval for the End Device in milliseconds.
 * The device will send keep-alive messages every 3000 milliseconds (3 seconds).
 */
#define ED_KEEP_ALIVE                   3000    /* 3000 millisecond */

/*
 * Define the endpoint number for the Zigbee device.
 * This endpoint is used to process commands related to light control.
 * Set to 10, meaning the device will handle commands on endpoint 10.
 */
#define HA_ESP_LIGHT_ENDPOINT           1
#define HA_ONOFF_SOLENOID_ENDPOINT_1    2
#define HA_ONOFF_SOLENOID_ENDPOINT_2    3
#define HA_ONOFF_SOLENOID_ENDPOINT_3    4
#define HA_ONOFF_SOLENOID_ENDPOINT_4    5
#define SOLENOID_1_GPIO GPIO_NUM_12 // Example GPIO pin for Solenoid 1
#define SOLENOID_2_GPIO GPIO_NUM_13 // Example GPIO pin for Solenoid 2
#define SOLENOID_3_GPIO GPIO_NUM_10 // Example GPIO pin for Solenoid 3
#define SOLENOID_4_GPIO GPIO_NUM_22 // Example GPIO pin for Solenoid 4


/*
 * Define the primary channel mask for the Zigbee transceiver.
 * This mask specifies which channels the Zigbee radio should operate on.
 * Using a predefined constant that allows all Zigbee channels.
 */
#define ESP_ZB_PRIMARY_CHANNEL_MASK     ESP_ZB_TRANSCEIVER_ALL_CHANNELS_MASK

/* Basic manufacturer information for the Zigbee device */

/*
 * Define the manufacturer name for the device.
 * The name "ESPRESSIF" is used, prefixed with the length of the string (9 characters).
 */
#define ESP_MANUFACTURER_NAME "\x09""ESPRESSIF"

/*
 * Define the model identifier for the device.
 * This uses a configuration value `CONFIG_IDF_TARGET`, with a length prefix of 7 characters.
 */
#define ESP_MODEL_IDENTIFIER "\x07"CONFIG_IDF_TARGET

/* Zigbee Device Configuration Macros */

/*
 * Macro to define the default configuration for a Zigbee End Device (ZED).
 * This includes setting the device role, enabling/disabling the install code policy,
 * and configuring network settings such as aging timeout and keep-alive interval.
 */
#define ESP_ZB_ZED_CONFIG()                                         \
    {                                                               \
        .esp_zb_role = ESP_ZB_DEVICE_TYPE_ED,                       /* Set device role to End Device (ED) */ \
        .install_code_policy = INSTALLCODE_POLICY_ENABLE,           /* Set install code policy (disabled in this example) */ \
        .nwk_cfg.zed_cfg = {                                        \
            .ed_timeout = ED_AGING_TIMEOUT,                         /* Set ED aging timeout */ \
            .keep_alive = ED_KEEP_ALIVE,                            /* Set keep-alive interval */ \
        },                                                          \
    }

/*
 * Macro to define the default radio configuration.
 * This includes setting the radio mode to its native Zigbee mode.
 */
#define ESP_ZB_DEFAULT_RADIO_CONFIG()                           \
    {                                                           \
        .radio_mode = ZB_RADIO_MODE_NATIVE,                     /* Set radio mode to native Zigbee mode */ \
    }

/*
 * Macro to define the default host configuration.
 * This includes setting the host connection mode, which in this case is none.
 */
#define ESP_ZB_DEFAULT_HOST_CONFIG()                            \
    {                                                           \
        .host_connection_mode = ZB_HOST_CONNECTION_MODE_NONE,   /* Set host connection mode to none */ \
    }

**Comment by xieqinan** [comment]
@xGreenPandax ,

Good job. If the `esp-zigbee-lib` and `esp-zboss-lib` versions are higher than v1.4.0, the ZCL data model cannot be reused. You'll need to create and register the model for each endpoint, just like the example you provided [here](https://github.com/espressif/esp-zigbee-sdk/issues/407#issuecomment-2391243470).

By the way, I think this issue has been addressed by yourself, could you please consider closing it?

**Comment by Gazelle84** [comment]
Closing post as this appears to be working for others.

**Comment by artc7** [comment]
> [@Gazelle84](https://github.com/Gazelle84) ,
> 
> The code below registers five endpoints to the device. You can use it as a reference for your project.
> 
> ```
>     esp_zb_on_off_switch_cfg_t switch_cfg = ESP_ZB_DEFAULT_ON_OFF_SWITCH_CONFIG();
>     esp_zb_ep_list_t *ep_list = esp_zb_ep_list_create();
>     for (int i = 0; i < 5; i++) {
>         esp_zb_endpoint_config_t endpoint_config = {
>             .endpoint = HA_ONOFF_SWITCH_ENDPOINT + i,
>             .app_profile_id = ESP_ZB_AF_HA_PROFILE_ID,
>             .app_device_id = ESP_ZB_HA_ON_OFF_SWITCH_DEVICE_ID,
>             .app_device_version = 0,
>         };
>         zcl_basic_manufacturer_info_t info = {
>             .manufacturer_name = ESP_MANUFACTURER_NAME,
>             .model_identifier = ESP_MODEL_IDENTIFIER,
>         };
>         esp_zb_ep_list_add_ep(ep_list, esp_zb_on_off_switch_clusters_create(&switch_cfg), endpoint_config);
>         esp_zcl_utility_add_ep_basic_manufacturer_info(ep_list, HA_ONOFF_SWITCH_ENDPOINT + i, &info);
>     }
>     esp_zb_device_register(ep_list);
> ```

Sorry if the question is trivial, I'm just starting with Zigbee devices, but after registering the endpoints like this, shouldn't five on/off switches appear in the Exposes tab in Zigbee2MQTT?
