### ISSUE TITLE
Identify when a device is offline (TZ-1099)

### ISSUE THREAD

**Issue by diazmanuel** [espressif/esp-zigbee-sdk#417]
### Question

I would like to know if the coordinator has any way of knowing when a device is offline, both synchronously and asynchronously.

1. asynchronously I would like to know if there is any signal that is triggered or a handler that we can register to know if a device is offline, for example when a device is not emitting the zigbee beacon.

2. synchronously I would like to read some type of table or implement a method to know if the device is online, for example with the function that I requested in #360 

As I mentioned before, all this should be done from the coordinator

**Comment by xieqinan** [comment]
@diazmanuel ,

> asynchronously I would like to know if there is any signal that is triggered or a handler that we can register to know if a device is offline, for example when a device is not emitting the zigbee beacon.

The esp-zigbee-sdk does not provide a handler to indicate when a device is offline, but you can check the neighbor table to determine the device's status. If the device is an end device and the end device timeout has been reached, it will be removed from the neighbor table. If the device is a router and the link status has not been updated within 60 seconds, the outgoing cost for the expired router will be set to 0.

> synchronously I would like to read some type of table or implement a method to know if the device is online, for example with the function that I requested in https://github.com/espressif/esp-zigbee-sdk/issues/360

You can use some simple ZDO commands to check if the device is online, such as `esp_zb_zdo_active_ep_req()`. If the device is unreachable, the request will trigger a timeout status in the user callback within 5 seconds. By the way, we are adding the support for the `zdo_mgmt_lqi_req()`.


Could you please provide a detailed description about your application?
