### ISSUE TITLE
How to get callback of custom attribute added in standard cluster? (TZ-1118)

### ISSUE THREAD

**Issue by mundevx** [espressif/esp-zigbee-sdk#421]
### Question

    
I am adding custom attribute 0xE100 in ESP_ZB_ZCL_CLUSTER_ID_COLOR_CONTROL as per tuya documentation , but didn't get the callback for this 0xE100 attribute but getting callback of other standard attributes.
This is the code: 
esp_zb_cluster_add_attr(esp_zb_color_cluster, ESP_ZB_ZCL_CLUSTER_ID_COLOR_CONTROL, 0xE100,
                            ESP_ZB_ZCL_ATTR_TYPE_U48, ESP_ZB_ZCL_ATTR_ACCESS_READ_WRITE | ESP_ZB_ZCL_ATTR_ACCESS_REPORTING, &color_temp);

When i update the attribute 0xE100, then it changes the color cluster UI in Tuya App, but no callback i am getting in espressif when things are reversed.

**Comment by lpy4105** [comment]
The callback will be trigger when the write operation succeed.

Can you share with the logs and preferably with the wireshark pcap file.
