### ISSUE TITLE
Obtaining at compile/runtime the ESP Zigbee Library version? (TZ-1137)

### ISSUE THREAD

**Issue by monty68** [espressif/esp-zigbee-sdk#429]
### Question

Can we obtain the version number/details of the ESP Zigbee library version at compile time and/or at runtime?

For ZBoss, there is the zb_get_version() function.

**Comment by xieqinan** [comment]
@monty68 ,

> Can we obtain the version number/details of the ESP Zigbee library version at compile time and/or at runtime?

The esp-zigbee-sdk v1.5.1 has already supported this feature, please refer to https://github.com/espressif/esp-zigbee-sdk/blob/main/components/esp-zigbee-lib/include/esp_zigbee_core.h#L961.

**Comment by xieqinan** [comment]
Hi @monty68 ,

Does this feature https://github.com/espressif/esp-zigbee-sdk/issues/429#issuecomment-2419191799 meet your requirement? If yes, please consider closing this issue.

**Comment by monty68** [comment]
Could we not have a simple #define in the header as well?

**Comment by xieqinan** [comment]
> Could we not have a simple #define in the header as well?

I cannot clearly understand your request; could you please provide more details about this requirement?
