### ISSUE TITLE
What is the max amount of routers in a network?  (TZ-1174)

### ISSUE THREAD

**Issue by BaWe155** [espressif/esp-zigbee-sdk#440]
### Question

I get an ERROR: Extended status 87 (ZPS_XS_E_NO_FREE_EXTENDED_ADDR) by 21 routers in a network.

What is the max number of routers in a network?

What is the size of the following tables in a router or coordinator: 
- mac address table
- routing table
- address_map tables
How to increase these tables?

**Comment by chshu** [comment]
@BaWe155 You can adjust the supported network scale with this API: [esp_zb_overall_network_size_set()](https://docs.espressif.com/projects/esp-zigbee-sdk/en/latest/esp32/api-reference/esp_zigbee_core.html#_CPPv431esp_zb_overall_network_size_set8uint16_t).

**Comment by BaWe155** [comment]
@chshu Thank you, is this for a coordinator or also for routers?

**Comment by chshu** [comment]
@BaWe155 For both coordinator and routers. Please share the device logs if you still see the issue after the change.
