### ISSUE TITLE
Zigbee DeviceID for wind speed sensors (TZ-1213)

### ISSUE THREAD

**Issue by lboue** [espressif/esp-zigbee-sdk#450]
Hello,

Is there a Zigbee DeviceID for wind speed sensors?
I haven't found one here:

https://github.com/espressif/esp-zigbee-sdk/blob/029f62b8c58e0f9bf673f5e668005c35907a0cb7/components/esp-zigbee-lib/include/zcl/esp_zigbee_zcl_common.h#L79-L120

Best regards

**Comment by lpy4105** [comment]
Hi @lboue,

Here only defines the device ID used by HA standard, and there is no ID for wind speed sensor. You can use a generic one, i.e `ESP_ZB_HA_SIMPLE_SENSOR_DEVICE_ID`.

**Comment by lboue** [comment]
Thanks
