### ISSUE TITLE
Does the current esp-zigbee-sdk support low power applications for ESP32-H2? (TZ-171)

### ISSUE THREAD

**Issue by diazmanuel** [espressif/esp-zigbee-sdk#46]
So The other day I bought some esp32H2 development boards and I would like to know if the sdk is already in a version that allows working with these devices in low consumption to create end devices. that the consumption is truly what the datasheet specifies and that it allows light and deep sleep without losing the zigbee network.

Thanks

**Comment by xieqinan** [comment]
@diazmanuel ,
The low-power feature for Zigbee is currently being tested internally and is expected to be available in the coming months.

**Comment by diazmanuel** [comment]
@xieqinan okey thanks you for the quick response

**Comment by joshelboy** [comment]
Hi, I am also interested in this. Are there any updates/docs on this topic?

**Comment by chshu** [comment]
@joshelboy @diazmanuel The Zigbee sleepy device example is available here: https://github.com/espressif/esp-zigbee-sdk/tree/main/examples/esp_zigbee_sleep/sleepy_end_device

**Comment by joshelboy** [comment]
@chshu Great! Needed this for my bachelor thesis, sorry for commenting this on two issues with the same question 😅
