### ISSUE TITLE
HA with an ESP32 Zigbee switch and light end device won't find short address.  (TZ-1244)

### ISSUE THREAD

**Issue by djorr5** [espressif/esp-zigbee-sdk#464]

**Comment by djorr5** [comment]
I jumped the gun. Sorry. 0xffff is what I should have been using.

**Comment by xieqinan** [comment]
@djorr5 

The `esp_zb_zdo_find_on_off_light()` allows you to locate the on/off cluster on the `addr_of_interest` device within the network. If `dst_nwk_addr` is set to `0xffff`, all RxWhenIdle devices will receive the command, and only the device with the short address matching `addr_of_interest` will respond.

**Comment by djorr5** [comment]
Interesting. I was just mucking around with it and with this struct:

`            find_req.addr_of_interest = 0xffff;
            find_req.dst_nwk_addr = 0xffff;`

The `esp_zb_zdo_find_on_off_light()` function actually finds the light end device and succesfully binds. As I only have 1 currently on the network I didn't worry about iterating or seeing if it discovers more than 1 end device this way. But are you saying that because the addr_of_interest is 0xffff it shouldn't find any end devices?

**Comment by xieqinan** [comment]
> But are you saying that because the addr_of_interest is 0xffff it shouldn't find any end devices?

Yes, I think so.

**Comment by djorr5** [comment]
Well it does find the light example with addr_of_interest = 0xffff
