### ISSUE TITLE
To deploy a Zigbee mesh (TZ-172)

### ISSUE THREAD

**Issue by Oscarren22** [espressif/esp-zigbee-sdk#47]
I am working with ESP32-C6 devices for development, and I want to create a mesh with around 200 devices using ESP32-H2,
I have been testing your Zigbee examples with good results, but I still don't know how to implement the mesh. I want to connect all the devices through the gateway.

Could you please guide me on how to do this?

**Comment by xieqinan** [comment]
Hi @Oscarren22,

There are three types of devices in Zigbee: coordinator, router, and end device.

In most cases, you would need a Zigbee gateway as the coordinator to establish the network and commission the joining devices. If you intend to create a Zigbee mesh network with 200 nodes using a gateway, it is essential to utilize routers as relay nodes. These routers will connect other end devices, extend the range of the Zigbee network, alleviate the traffic burden, and route network messages. Deploying routers according to the actual environment is crucial. By ensuring a reasonable and suitable network topology, the Zigbee network mechanism will facilitate the formation of the network mesh.

Feel free to discuss any issues or problems you may have in this regard.

**Comment by xieqinan** [comment]
Hi,
If the issue has been resolved, please close it.

**Comment by chshu** [comment]
The mesh network could be established automatically based on the physical topology in the field. @Oscarren22 Please reopen if any follow up questions.
