### ISSUE TITLE
[feature request] read attribute response callback (TZ-186)

### ISSUE THREAD

**Issue by BogatovT** [espressif/esp-zigbee-sdk#48]
Hello!
I'm developing coordinator firmware on C6 SoC. I have many different devices in network and need to request their attributes.
Using esp_zb_add_read_attr_resp_cb() function i cant to distinguish which device sent response. It complicates to requesting many attributes from many endpoints and many devices.
Can your team add another read attribute response callback or add device address and endpoint to esp_zb_read_attr_resp_callback_t struct?

**Comment by xieqinan** [comment]
@BogatovT ,
Thank you for your suggestions, The feature will be added  in next week.

**Comment by xieqinan** [comment]
Hello,
The feature request has been implemented, please refer to the newest [esp-zigbee-sdk](https://github.com/espressif/esp-zigbee-sdk/blob/main/examples/esp_zigbee_customized_devices/customized_client/main/esp_HA_customized_switch.c#L227C18-L227C43).
