### ISSUE TITLE
ZDO simple description response receive but ZIGBEE stack reports request timeout (TZ-1300)

### ISSUE THREAD

**Issue by vanbuong** [espressif/esp-zigbee-sdk#485]
### Question

I tried to pair Tuya Smart Plug but when requesting a simple descriptor request, I can see the response from a data indication callback but the response handler callback isn't triggered, and stack printed request timeout.

![image](https://github.com/user-attachments/assets/5e32dddf-bdd7-4be7-b62e-cb260835d64a)
Analyzing the packet sniffer, there are 2 more bytes in this response. It seems the wrong response format caused this issue.

**Comment by xieqinan** [comment]
> Analyzing the packet sniffer, there are 2 more bytes in this response. It seems the wrong response format caused this issue.

Yes, I have confirmed this issue. The stack compares the received frame length with the `simple descriptor length`. If they are not equal, the stack considers it an invalid frame.
