### ISSUE TITLE
Is there way to stop attribute update in callback??? (TZ-1395)

### ISSUE THREAD

**Issue by damian-kurek-wizzdev** [espressif/esp-zigbee-sdk#505]
### Question

Is there a way to stop the attribute write operation?
I tried to return ESP_FAIL when I got ESP_ZB_CORE_SET_ATTR_VALUE_CB_ID in core_zb_callback, but it does not work.

**Comment by xieqinan** [comment]
The Zigbee ZCL specification defines the valid range for cluster attributes and determines whether the write operation should be stopped. If you wish to define a custom rule to override this, you can call `esp_zb_zcl_custom_cluster_handlers_update()` to update the original rule. Please note that all identical clusters on the device will follow the same rule.
