### ISSUE TITLE
Unable to use more than 5 endpoints as a device (TZ-199)

### ISSUE THREAD

**Issue by nomis** [espressif/esp-zigbee-sdk#51]
I need at least 34 endpoints but I'm unable to use more than 5 because the rest of them don't appear.

Example project: https://github.com/espressif/esp-zigbee-sdk/compare/main...nomis:esp-zigbee-sdk:multiple-endpoints
I'm running this on an ESP32-C6 connecting to a SONOFF "Zigbee 3.0 USB Dongle Plus V2".

Whatever order I create them in, only the first 5 endpoints show up (and they show up in the order that `esp_zb_ep_list_add_ep()` was called):
![Screenshot from 2023-07-23 16-13-35](https://github.com/espressif/esp-zigbee-sdk/assets/70171/59499570-4fd3-4cb8-9779-cfb023e27844)

**Comment by nomis** [comment]
This value needs to be increased in the zboss library and then recompiled by espressif:
```
#ifndef ZB_MAX_EP_NUMBER
/* max supported EP number, increase if needed */
/** Maximum number of supported endpoints per device */
#define ZB_MAX_EP_NUMBER 5U
#endif
```

**Comment by xieqinan** [comment]
@nomis , Thank you for your information; the MACRO will be added as soon as possible.

**Comment by xieqinan** [comment]
Hi,
The `ZB_MAX_EP_NUMBER` has been enlarged to 35 in the recent version. Distributing your endpoints to more devices may be more helpful in implementing your application.

For other topics related to esp-zigbee-sdk, they can be discussed in an new issue.

**Comment by nomis** [comment]
> Distributing your endpoints to more devices may be more helpful in implementing your application.

No, the zboss SDK needs to be modified so that memory is allocated dynamically and this arbitrary limit is removed. The setting only exists because it assumes you have the source code and can rebuild it to change the fixed size arrays.
