### ISSUE TITLE
[Feature request] Support for array, charstring or octetstring datatypes for attributes. (TZ-208)

### ISSUE THREAD

**Issue by petergjoel** [espressif/esp-zigbee-sdk#57]
When registering any attribute of flexible sized fields for `esp_zb_custom_cluster_add_custom_attr`, I get:
```
ESP_ZIGBEE_ATTRIBUTE: The data type of the value is not supported
```
It would make the Zigbee functionality much more flexible.

**Comment by xieqinan** [comment]
Hi @petergjoel ,
Thank you for your suggestion, the feature will been added as soon as possiable.

**Comment by xieqinan** [comment]
Hello,
 The issue has been resolved in the  [esp-zigbee-sdk](https://github.com/espressif/esp-zigbee-sdk)  master branch, which includes some breaking changes. Would you be able to give it another try?
