### ISSUE TITLE
Stop adding `-Wno-strict-prototypes` to the CFLAGS for the entire project (TZ-209)

### ISSUE THREAD

**Issue by nomis** [espressif/esp-zigbee-sdk#58]
Both this component and esp-zboss-lib are adding `-Wno-strict-prototypes` to the CFLAGS for all files.

This results in the following warning when compiling any C++ file:
```
cc1plus: warning: command-line option '-Wno-strict-prototypes' is valid for C/ObjC but not for C++
```

It makes it impossible to enable `-Werror` for C++ files because the command line option is a warning that can't be suppressed:
```
cc1plus: error: command-line option '-Wno-strict-prototypes' is valid for C/ObjC but not for C++ [-Werror]
cc1plus: all warnings being treated as errors
```

**Comment by xieqinan** [comment]
@nomis,
Thank you for your suggestion. The issue has been fixed,  it will be updated in this week.
