### ISSUE TITLE
When the device joins the network, it will send a Leave request to the device (TZ-211)

### ISSUE THREAD

**Issue by Zmmfly** [espressif/esp-zigbee-sdk#60]
Hi, I can't tell for myself; is this a device issue, or a protocol stack issue?

## First problem:
![20230801154337](https://github.com/espressif/esp-zigbee-sdk/assets/4443813/7dc60546-f16f-4cef-b808-cfbafc6d56c0)

### The first ACK is not set pending:

![DataRequest_ACK1](https://github.com/espressif/esp-zigbee-sdk/assets/4443813/49ffad6b-887e-4146-8238-12f3c4f72316)

### But the second ACK sets pending:

![DataRequestACK2](https://github.com/espressif/esp-zigbee-sdk/assets/4443813/7842b08a-6009-4473-8aac-0e66d224fe11)

### And, immediately following the ACK, a Leave frame is replied:
![DataRequestLeave](https://github.com/espressif/esp-zigbee-sdk/assets/4443813/a6f08c6e-6ad3-4e97-b554-d2700cfcd7e8)

Then, repeat this loop over and over again, join the network -> report attributes -> Request Data -> leave -> start from scratch.
I have to restart the coordinator once so that the device will become normal into the network.

## Second problem:
After the network access process in the startup phase, no matter how long I set the permit join time, the Association Permit is always not set in the Beacon that responds to the BeaconRequest of the device.

![AssociationPermit](https://github.com/espressif/esp-zigbee-sdk/assets/4443813/720ae9de-5eaa-463b-88bc-89905e6bcf36)

And, after executing esp_zb_zdo_permit_joining_req, it always times out around 4600 milliseconds.

```shell
$ zb_permitJoin -t 1
permit join req, addr: ffff, time: 1, tc_significance: 0
I (1370368) zbRCP: zb_permit_join_cb, status: 1, hex: 1
I (1374952) ESP_ZIGBEE_API_ZDO: ZDO permit join request timeout!
W (1374952) ESP_ZIGBEE_API_ZDO: The tsn of callback is not found
W (1374952) ESP_ZIGBEE_API_ZDO: The tsn of callback is not found and can't remove

$ zb_permitJoin -t 255
permit join req, addr: ffff, time: 255, tc_significance: 0
I (1379123) zbRCP: zb_permit_join_cb, status: 254, hex: fe
I (1383725) ESP_ZIGBEE_API_ZDO: ZDO permit join request timeout!
W (1383725) ESP_ZIGBEE_API_ZDO: The tsn of callback is not found
W (1383725) ESP_ZIGBEE_API_ZDO: The tsn of callback is not found and can't remove
```

**Comment by xieqinan** [comment]
Hi @Zmmfly,
This issue is similar to #21. It may is helpful for you. Could you please refer to it and try again?

**Comment by Zmmfly** [comment]
Hi @xieqinan, thanks for the reminder, setting `esp_zb_secur_link_key_exchange_required_set` to false successfully resolved the issue.

I found a solution to the second problem. Before calling `esp_zb_zdo_permit_joining_req`, you need to call `zb_nlme_permit_joining_request` with the same "time" as a parameter. After that, the Association Permit in Beacon will be set, so that the device can join the network.
