### ISSUE TITLE
Temperature cluster (TZ-237)

### ISSUE THREAD

**Issue by delyan-boychev** [espressif/esp-zigbee-sdk#74]
I am struggling to understand how to send the temperature from the client device and after that how to receive the callback when I receive the temperature. Is there any example because the on_off light is not understandable?

**Comment by Zmmfly** [comment]
Hi @delyan-boychev,

Initially, I was also unsure about how to use this library.

For your specific case, if you want to receive the temperature, you need to understand the zigbee cluster model. The value is uploaded to the coordinator via an attribute report request.

Thus, you just need to set the attribute report callback using `esp_zb_device_add_report_attr_cb`. Currently, there isn't a context pointer in the parameters, so you'll need to handle that on your own.

To send temperature readings, you'll need to send an attribute report request using `esp_zb_zcl_report_attr_cmd_req`. Please refer to the documentation to get more details on this API.

**Comment by xieqinan** [comment]
@Zmmfly 
Your understanding is very accurate.

**Comment by xieqinan** [comment]
@delyan-boychev 
The `esp_zb_zcl_report_attr_cmd_req()` function can be invoked to solicit temperature sensor value reporting. This value will be received through the function  registered via `esp_zb_device_add_report_attr_cb()`.

**Comment by delyan-boychev** [comment]
Thank you very much @xieqinan and @Zmmfly! However, esp_zb_zcl_report_attr_cmd_t has not property to set the value. So how to set the value in the request and send it?

**Comment by Tropaion** [comment]
@delyan-boychev updating and sending value looks something like this:
```
/* Create report request command */
static esp_zb_zcl_report_attr_cmd_t temperature_cmd_req = {
        .zcl_basic_cmd.src_endpoint = HA_EE31_ENDPOINT,
        .address_mode = ESP_ZB_APS_ADDR_MODE_DST_ADDR_ENDP_NOT_PRESENT,
        .clusterID = ESP_ZB_ZCL_CLUSTER_ID_TEMP_MEASUREMENT,
        .cluster_role = ESP_ZB_ZCL_CLUSTER_SERVER_ROLE,
        .attributeID = ESP_ZB_ZCL_ATTR_TEMP_MEASUREMENT_VALUE_ID
    };


/* Measurement values */
float temp = 30;

/* Convert to correct attribute format */
int16_t attr_temp = (int16_t)(temp * 100);

/* Write temperature attribute */
esp_zb_zcl_status_t state = esp_zb_zcl_set_attribute_val(ENDPOINT, ESP_ZB_ZCL_CLUSTER_ID_TEMP_MEASUREMENT, ESP_ZB_ZCL_CLUSTER_SERVER_ROLE, ESP_ZB_ZCL_ATTR_TEMP_MEASUREMENT_VALUE_ID, &attr_temp, false);
    
/* Check for error */
if(state != ESP_ZB_ZCL_STATUS_SUCCESS) { ESP_LOGE(TAG, "Setting temperature attribute failed!"); }

/* Request sending new temperature */
state = esp_zb_zcl_report_attr_cmd_req(&temperature_cmd_req);
```
I currently have a [project ](https://github.com/Tropaion/ZigBee_SmartMeter_Reader)WIP which uses these command if you want to look into it.

**Comment by delyan-boychev** [comment]
Thank you @Tropaion! It is really helpful, but I can't find where in the code you have a callback when you receive temp measurement.

**Comment by Tropaion** [comment]
Because I'm only sending the temperature data and not receiving it, sorry I can only help you with that. I'm using a common coordinator in Home Assistant to receive data.

**Comment by vedatbotuk** [comment]
Hi @delyan-boychev  do you have any server-client example with temperature sensor. I still don't have it.

**Comment by delyan-boychev** [comment]
I am using the dimmable light example and parsing the temperature in the light level. It works perfectly!

**Comment by vedatbotuk** [comment]
Thanks, that works really good.

**Comment by teleger** [comment]
> I am using the dimmable light example and parsing the temperature in the light level. It works perfectly!

Where can I see such an example, I urgently need such a code reference, I have not made the code work for three days, I really need help now, thank you

**Comment by vedatbotuk** [comment]
Look in to this code. I hope it is helpful for you.
https://github.com/vedatbotuk/selforganized_802.15.4_network_with_esp32/tree/main/RFD/main

**Comment by teleger** [comment]
> Look in to this code. I hope it is helpful for you. https://github.com/vedatbotuk/selforganized_802.15.4_network_with_esp32/tree/main/RFD/main

Thank you for your quick reply, your writing is very good! I do not see any obvious trace of receiving temperature data in the code of your coordinator. It seems to me that there is no need to explicitly prove that the coordinator has received temperature data.

**Comment by vedatbotuk** [comment]
Hi, you have to look in to RFD.
COORDINATOR and FFD are not ready and will not work.

**Comment by teleger** [comment]
> Hi, you have to look in to RFD. COORDINATOR and FFD are not ready and will not work.


I saw your action of writing the temperature value report, but I couldn't find the code to receive the temperature data. Could you please tell me where it is, thank you very much

**Comment by vedatbotuk** [comment]
I use an external COORDINATOR/SONOFF Zigbee 3.0 USB Dongle E ZigBee) now, not an esp32-h2 or esp32-c6. With SONOFF Dongle will you get date from RFD device.
My COORDINATOR code is not correct, and can get data from RFD.

**Comment by teleger** [comment]
> 我现在使用外部 COORDINATOR/SONOFF Zigbee 3.0 USB Dongle E ZigBee)，而不是 esp32-h2 或 esp32-c6。使用 SONOFF Dongle，您可以从 RFD 设备获取数据。 我的COORDINATOR代码不正确，可以从RFD获取数据。

Anyway, I appreciate you taking the time to answer my questions. Thank you！！
