### ISSUE TITLE
esp_zb_zdo_match_cluster() not working  (TZ-243)

### ISSUE THREAD

**Issue by mallaprashant** [espressif/esp-zigbee-sdk#78]
We have released a new version of esp_zigbee_sdk that includes the common function to find the matched cluster `esp_zb_zdo_match_cluster `  please use the updated `esp_zb_zdo_match_desc_req_param_t` to create your required cluster list . 

_Originally posted by @abdulrehmanee12 in https://github.com/espressif/esp-zigbee-sdk/issues/42#issuecomment-1635352085_
            
I used "esp_zb_zdo_match_cluster" to find door lock server cluster.
I got this log output 
" ESP_ZIGBEE_API_ZDO: The tsn of callback is not found
   ESP_ZIGBEE_API_ZDO: The tsn of callback is not found and can't remove"

I dont know where to set tsn callback . I may be wrong. can someone explain how it works??

**Comment by xieqinan** [comment]
Hi @mallaprashant ,
The log indicates your device has not find the door lock server cluster, please attach your code which is helpful for us to address your issue.

**Comment by mallaprashant** [comment]
Hello @xieqinan, I replaced "esp_zb_zdo_find_on_off_light()" with "esp_zb_zdo_match_cluster()"  in esp_zb_customized_devices  example. As you can see below it says no device found but switch and light application is working perfectly fine.

![Screenshot 2023-08-23 100720](https://github.com/espressif/esp-zigbee-sdk/assets/63976004/a0588d4f-aeaf-4fa4-aec5-c1f4a8e59ee2)

**Comment by xieqinan** [comment]
Hi,

Could you try to use the following code for your esp_zb_customized_devices_example to find the specified cluster?

```
esp_zb_zdo_match_desc_req_param_t find_req;
uint16_t cluster_list[] = {ESP_ZB_ZCL_CLUSTER_ID_ON_OFF};
find_req.dst_nwk_addr = 0x0000;
find_req.addr_of_interest = 0x0000;
find_req.profile_id = ESP_ZB_AF_HA_PROFILE_ID;
find_req.num_in_clusters = 1;
find_req.num_out_clusters = 0;
find_req.cluster_list = cluster_list;
esp_zb_zdo_match_cluster(&find_req, user_find_cb, NULL);
```

**Comment by mallaprashant** [comment]
Thanks @xieqinan it worked.
As for my door lock client is on Coordinator. This is what I came with but facing problem in rejoin after coordinator device is reset.

>         
        esp_zb_zdo_match_desc_req_param_t find_req;
        uint16_t cluster_list[] = {ESP_ZB_ZCL_CLUSTER_ID_DOOR_LOCK};
        find_req.dst_nwk_addr = dev_annce_params->device_short_addr;
        find_req.addr_of_interest = dev_annce_params->device_short_addr;
        find_req.profile_id = ESP_ZB_AF_HA_PROFILE_ID;
        find_req.num_in_clusters = 1;
        find_req.num_out_clusters = 0;
        find_req.cluster_list = cluster_list;
        esp_zb_zdo_match_cluster(&find_req, user_find_cb, NULL);

**Comment by xieqinan** [comment]
Hello,

Do you mean that the coordinator with a door lock client will reboot when the door lock server rejoins it?

Could you please tell me how to reproduce this behavior?

**Comment by mallaprashant** [comment]
@xieqinan No, it doesn't reboot when the door lock server rejoins. I manually rebooted the coordinator device to check if end device reconnects to coordinator or not.

But I encounter another problem, I try to send unlock command but got this error on server side 
 "ESP_ZIGBEE_CORE: Device callback id(0x5f) has not been handled"


client-side code 
>       
        esp_zb_zcl_lock_unlock_door_cmd_t cmd_req;
        cmd_req.zcl_basic_cmd.dst_addr_u.addr_short = door_lock_info.short_addr;
        cmd_req.zcl_basic_cmd.dst_endpoint = door_lock_info.endpoint;
        cmd_req.zcl_basic_cmd.src_endpoint = HA_ESP_DOOR_LOCK_ENDPOINT;
        cmd_req.address_mode = ESP_ZB_APS_ADDR_MODE_16_ENDP_PRESENT;
        esp_zb_zcl_unlock_door_cmd_req(&cmd_req);

For binding 

> 
       static void bind_cb(esp_zb_zdp_status_t zdo_status, void *user_ctx)
    {
        if (zdo_status == ESP_ZB_ZDP_STATUS_SUCCESS) {
            ESP_LOGI(TAG, "Bind response from address(0x%x), endpoint(%d) with status(%d)", ((zdo_info_user_ctx_t *)user_ctx)- 
                       >short_addr,
                     ((zdo_info_user_ctx_t *)user_ctx)->endpoint, zdo_status);
            /* configure report attribute command */
            esp_zb_zcl_config_report_cmd_t report_cmd;
            bool report_change = 0;
            report_cmd.zcl_basic_cmd.dst_addr_u.addr_short = door_lock_info.short_addr;
            report_cmd.zcl_basic_cmd.dst_endpoint = door_lock_info.endpoint;
            report_cmd.zcl_basic_cmd.src_endpoint = HA_ESP_DOOR_LOCK_ENDPOINT;
            report_cmd.address_mode = ESP_ZB_APS_ADDR_MODE_16_ENDP_PRESENT;
            report_cmd.clusterID = ESP_ZB_ZCL_CLUSTER_ID_DOOR_LOCK;
            report_cmd.attributeID = ESP_ZB_ZCL_ATTR_DOOR_LOCK_NUM_OF_DOOR_OPEN_EVENTS_ID;
            report_cmd.attrType = ESP_ZB_ZCL_ATTR_TYPE_U32;
            report_cmd.min_interval = 0;
            report_cmd.max_interval = 30;
            report_cmd.reportable_change = (void*)&report_change;
            esp_zb_zcl_config_report_cmd_req(&report_cmd);
        }
    }


server-side code 

> 
         static esp_err_t attr_cb(const esp_zb_zcl_set_attr_value_message_t message)
        {
            esp_err_t ret = ESP_OK;
            bool door_lock_state = 0;
            if (message.info.status == ESP_ZB_ZCL_STATUS_SUCCESS) {
                ESP_LOGI(TAG, "Received message: endpoint(0x%x), cluster(0x%x), attribute(0x%x), data size(%d)", 
             message.info.dst_endpoint,
                         message.info.cluster, message.attribute, message.data.size);
                if (message.info.dst_endpoint == HA_DOOR_LOCK_ENDPOINT) {
                    if (message.info.cluster ==  ESP_ZB_ZCL_CLUSTER_ID_DOOR_LOCK) {
                        if (message.attribute == ESP_ZB_ZCL_ATTR_DOOR_LOCK_NUM_OF_DOOR_OPEN_EVENTS_ID && 
           message.data.type == ESP_ZB_ZCL_ATTR_TYPE_U32) {
                            door_lock_state = message.data.value ? *(uint32_t *)message.data.value : door_lock_state;
                            ESP_LOGI(TAG, "Door lock sets to %s", door_lock_state ? "OPEN" : "CLOSED");
                            printf("The attribute value received is %d", door_lock_state);
                        }
                    }
                } 
            } else {
                ESP_LOGE(TAG, "Received message: status(%d) error", message.info.status);
                ret = ESP_ERR_INVALID_ARG;
            }
            return ret;
        }


Can you Help me with this

**Comment by xieqinan** [comment]
Alright, it appears that the device callback ID 0x5f is not currently supported. In the upcoming release version, we are planning to introduce a common solution to support the serial issue. Thank you for bringing this to our attention.

**Comment by mallaprashant** [comment]
@xieqinan thank you for your reply. I'm looking forward to the upcoming release of this SDK. I hope it becomes available soon.

**Comment by xieqinan** [comment]
Hello,
For this issue, We provide a function `esp_zb_zcl_device_cb_id_cb()` for user to access the raw DEVICE_CB_ID of ZBOSS and handle it in esp-zigbee-lib v0.9.1.

You can refer to the following code to address it.

```
#include "zboss_api.h"
bool device_cb(uint8_t bufid)
{
    if (ZB_ZCL_DEVICE_CMD_PARAM_CB_ID(bufid) == 0x5f) {
        zb_zcl_door_lock_read_lock_door_res_payload_t *payload =
            ZB_ZCL_DEVICE_CMD_PARAM_OUT_GET(bufid, zb_zcl_door_lock_read_lock_door_res_payload_t);
        // indicate the status of door lock for the stack to response. 
        payload->status = ZB_ZCL_STATUS_SUCCESS;
        ZB_ZCL_DEVICE_CMD_PARAM_STATUS(bufid) = RET_OK;
    }
    return true;
}

static void esp_zb_task(void *pvParameters)
{
    /* initialize Zigbee stack with Zigbee coordinator config */
    esp_zb_cfg_t zb_nwk_cfg = ESP_ZB_ZC_CONFIG();
    esp_zb_init(&zb_nwk_cfg);
    /* set the on-off switch device config */
    esp_zb_on_off_switch_cfg_t switch_cfg = ESP_ZB_DEFAULT_ON_OFF_SWITCH_CONFIG();
    esp_zb_ep_list_t *esp_zb_on_off_switch_ep = esp_zb_on_off_switch_ep_create(HA_ONOFF_SWITCH_ENDPOINT, &switch_cfg);
    esp_zb_device_register(esp_zb_on_off_switch_ep);
    esp_zb_zcl_device_cb_id_cb(device_cb);
    esp_zb_set_primary_network_channel_set(ESP_ZB_PRIMARY_CHANNEL_MASK);
    ESP_ERROR_CHECK(esp_zb_start(false));
    esp_zb_main_loop_iteration();
}

```

You can use the above way to handle others DEVICE_CB_IDs.

**Comment by mallaprashant** [comment]
@xieqinan thanks for the update. But I tried to send lock and unlock command using esp_zb_zcl_lock_door_cmd_req() from client device and used   esp_zb_add_cluster_privilege_command_cb(uint8_t endpoint, uint16_t cluster, uint16_t command, esp_zb_privilege_command_callback_t cb);   in server side. But [https://github.com/espressif/esp-zigbee-sdk/issues/75#issuecomment-1690163769](url) same happen to me as well. I tried to find information on this matter but was unsuccessful in doing so. can you provide some workflow or information on this matter.
