### ISSUE TITLE
How to get rssi? (TZ-245)

### ISSUE THREAD

**Issue by Tropaion** [espressif/esp-zigbee-sdk#79]
Hello,
I'm not sure how it works, but is there a way to get the RSSI from my esp router/end device?
I created an router with an temperature and humidity sensor, from which I successfully get the LQI value but not RSSI, which my company would need for an field test.
Or maybe do I need the RSSI Location Cluster, which is not implemeted (yet), for this?

**Comment by xieqinan** [comment]
Hello, 
Are you interested in obtaining the RSSI of an ESP Zigbee device?

Could you kindly share the method you employed to retrieve the LQI?

As of the current version, the RSSI API is not supported. However, there is a workaround available. You can utilize `esp_ieee802154_get_recent_rssi()` to access the RSSI value of the most recently received frame. It's important to note that this API only provides the RSSI for the latest received frame.

A more refined approach for obtaining RSSI will be introduced in an upcoming version.

**Comment by Tropaion** [comment]
Hello @xieqinan,
I didn't directly retrieve it, Home Assistant shows the LQI of the device but not RSSI.

**Comment by xieqinan** [comment]
OK, Let me know which kind way you expected to get  getting RSSI value.

**Comment by Tropaion** [comment]
I want it to be displayed here.
![image](https://github.com/espressif/esp-zigbee-sdk/assets/6797663/5657b16d-3b3e-4d29-9709-fb1fe39ce71b)
HomeAssistant successfully displays LQI from the device but always says `Unknown` for RSSI.

**Comment by BogatovT** [comment]
Yeah, it will be good to get RSSI in whole callback functions.

**Comment by chshu** [comment]
@Tropaion @BogatovT Adding RSSI to all the callbacks doesn't help with this issue.

There should be some tools used to connect the Zigbee device and HomeAssistant APP, could you check where does the HomeAssistant read the RSSI from? Actually I also wondering whether the LQI value is eported by Zigbee device or not.

**Comment by xieqinan** [comment]
@Tropaion,

> I want it to be displayed here. ![image](https://user-images.githubusercontent.com/6797663/262904443-5657b16d-3b3e-4d29-9709-fb1fe39ce71b.png) HomeAssistant successfully displays LQI from the device but always says `Unknown` for RSSI.

Regarding this issue, I believe there are two suggestions.

Firstly, please ensure that the ZCL Identify cluster has been created in your endpoint, as the 'diagnose' button is meant for sending identify commands.

Secondly, please ensure the RSSI function is visible as follows:
![image](https://github.com/espressif/esp-zigbee-sdk/assets/49604229/445a0c1b-29d8-40c8-9ed8-f0179cd9f0fe)


As a result, the `Diagnose` control panel will be displayed as follows:
![image](https://github.com/espressif/esp-zigbee-sdk/assets/49604229/bffdadf2-ea62-416a-a246-5f6cde128a53)

**Comment by Tropaion** [comment]
@xieqinan Thank you. Did you test this? Do you have a code example? Because I did the basic implementation of the identify cluster, but I didn't get LQI and RSSI. Maybe there is some mistake in my [implementation](https://github.com/Tropaion/ZigBee_SmartMeter_Reader/blob/main/software/zigbee/components/zigbee_electricity_meter/src/zb_electricity_meter.c#L195)?

**Comment by xieqinan** [comment]
Yes, I have already tested it. You just need to use the [HA_ON_OFF_LIGHT](https://github.com/espressif/esp-zigbee-sdk/tree/main/examples/esp_zigbee_HA_sample/HA_on_off_light) as the end device to join Home Assistant, then diagnose it.
Please note to click the RSSI icon to make it visible.

**Comment by Tropaion** [comment]
Ok, then I will try it again.

**Comment by chshu** [comment]
@Tropaion Please reopen if you have any follow up question on this topic.
