### ISSUE TITLE
error: implicit declaration of function 'esp_zb_device_add_set_attr_value_cb' (TZ-253)

### ISSUE THREAD

**Issue by tianrongqin** [espressif/esp-zigbee-sdk#87]
There is a problem when I build the esp-zigbee-sdk\examples\esp_zigbee_HA_sample\HA_on_off_light

error: implicit declaration of function 'esp_zb_device_add_set_attr_value_cb' [-Werror=implicit-function-declaration]
  109 |     esp_zb_device_add_set_attr_value_cb(attr_cb);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1.exe: some warnings being treated as errors
[884/893] Linking C static library esp-idf\spiffs\libspiffs.a
ninja: build stopped: subcommand failed.

**Comment by xieqinan** [comment]
Hello, 

We have updated the esp-zigbee-lib to version 0.9.3, introducing breaking changes while also presenting an improved approach for users to register callbacks within the most recent [esp-zigbee-sdk](https://github.com/espressif/esp-zigbee-sdk). The new usage can be referenced through [esp-zb-light](https://github.com/espressif/esp-zigbee-sdk/blob/main/examples/esp_zigbee_HA_sample/HA_on_off_light/main/esp_zb_light.c#L117).
